# Generated by Django 6.0.3 on 2026-03-19 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_historicalbook_visibility"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="book",
            name="genres",
        ),
        migrations.RemoveField(
            model_name="book",
            name="item_ptr",
        ),
        migrations.RemoveField(
            model_name="book",
            name="shelf",
        ),
        migrations.RemoveField(
            model_name="book",
            name="verlag",
        ),
        migrations.RemoveField(
            model_name="genre",
            name="parent_genre",
        ),
        migrations.RemoveField(
            model_name="historicalbook",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalbook",
            name="item_ptr",
        ),
        migrations.RemoveField(
            model_name="historicalbook",
            name="shelf",
        ),
        migrations.RemoveField(
            model_name="historicalbook",
            name="user",
        ),
        migrations.RemoveField(
            model_name="historicalbook",
            name="verlag",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
        migrations.DeleteModel(
            name="Shelf",
        ),
        migrations.DeleteModel(
            name="HistoricalBook",
        ),
        migrations.DeleteModel(
            name="Publisher",
        ),
    ]
