{{- if and .Values.frontend.enabled .Values.frontend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bubble.frontend.fullname" . }}
  labels:
    {{- include "bubble.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  {{- with .Values.frontend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.frontend.ingress.className }}
  ingressClassName: {{ .Values.frontend.ingress.className }}
  {{- end }}
  {{- if .Values.frontend.ingress.tls }}
  tls:
    {{- toYaml .Values.frontend.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.frontend.ingress.hosts }}
    {{- $host := .host }}
    - host: {{ $host | quote }}
      http:
        paths:
          {{- if $.Values.backend.enabled }}
          {{- range $.Values.frontend.ingress.backendPrefixes }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "bubble.backend.fullname" $ }}
                port:
                  number: {{ $.Values.backend.service.port }}
          {{- end }}
          {{- end }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "bubble.frontend.fullname" $ }}
                port:
                  number: {{ $.Values.frontend.service.port }}
    {{- end }}
{{- end }}
