# Generated by Django 6.0.3 on 2026-03-14 16:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
        ('items', '0005_remove_item_items_sale_or_rental_price_not_both_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, help_text='Snapshot of item name at event time', max_length=255)),
                ('action', models.CharField(choices=[('item_added', 'Item added'), ('item_removed', 'Item removed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_events', to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='collections.collection')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_events', to='items.item')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
