# Generated by Django 6.0.3 on 2026-03-16 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0002_collectionevent'),
        ('items', '0006_delete_itemembedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectionitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'item'), name='unique_item_per_collection', violation_error_message='This item is already in the collection.'),
        ),
    ]
