# Generated by Django 6.0.6 on 2026-06-14 07:05

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Backfill a unique slug for every existing collection from its name."""
    Collection = apps.get_model("collections", "Collection")
    for collection in Collection.objects.all().order_by("created_at"):
        base_slug = slugify(collection.name) or "collection"
        new_slug = base_slug
        counter = 1
        while (
            Collection.objects.filter(slug=new_slug)
            .exclude(pk=collection.pk)
            .exists()
        ):
            new_slug = f"{base_slug}-{counter}"
            counter += 1
        # Use a direct UPDATE to avoid bumping the auto_now `updated_at` column.
        Collection.objects.filter(pk=collection.pk).update(slug=new_slug)


def reverse_noop(apps, schema_editor):
    """No-op: the slug column is dropped by the reverse of AddField."""


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0003_unique_item_per_collection"),
    ]

    operations = [
        # Add the column without the uniqueness constraint so existing rows can
        # share the empty default until they are backfilled below.
        migrations.AddField(
            model_name="collection",
            name="slug",
            field=models.SlugField(
                blank=True,
                db_index=False,
                default="",
                help_text="URL-friendly identifier. Generated from the name by default, but can be customised.",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(populate_slugs, reverse_noop),
        # Now that every row has a distinct slug, enforce uniqueness.
        migrations.AlterField(
            model_name="collection",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly identifier. Generated from the name by default, but can be customised.",
                max_length=200,
                unique=True,
            ),
        ),
    ]
