# Generated by Django 6.0.3 on 2026-03-15 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0005_remove_item_items_sale_or_rental_price_not_both_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ItemEmbedding",
        ),
    ]
