# Generated by Django 6.0.3 on 2026-03-16 21:34

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0006_delete_itemembedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalitem",
            name="price",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                help_text="Price for sell/rent items (must be > 0). Leave blank for donate/borrow items. Rental price per hour (when sales type is rent).",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalitem",
            name="rental_period",
            field=models.CharField(
                blank=True,
                choices=[("h", "Hourly"), ("d", "Daily"), ("w", "Weekly")],
                default="h",
                help_text="Only used for formatting, price must always be per hour for rental items",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                help_text="Price for sell/rent items (must be > 0). Leave blank for donate/borrow items. Rental price per hour (when sales type is rent).",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="rental_period",
            field=models.CharField(
                blank=True,
                choices=[("h", "Hourly"), ("d", "Daily"), ("w", "Weekly")],
                default="h",
                help_text="Only used for formatting, price must always be per hour for rental items",
                max_length=1,
            ),
        ),
    ]
