# Generated by Django 6.0.3 on 2026-03-27 04:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_item_properties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='items_sell_rent_require_price',
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sales_type', 'sell'), _negated=True), ('price__isnull', False), _connector='OR'), name='items_sell_require_price'),
        ),
    ]
