# Generated by Django 6.0.3 on 2026-03-27 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_remove_rent_price_requirement'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='items_sell_require_price',
        ),
    ]
