# Generated by Django 6.0.3 on 2026-03-30 17:56

from django.db import migrations, models


def migrate_processing_to_draft(apps, schema_editor):
    """Move any items with status=1 (Processing) back to status=0 (Draft)."""
    Item = apps.get_model("items", "Item")
    Item.objects.filter(status=1).update(status=0)


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0010_remove_sell_price_requirement"),
    ]

    operations = [
        migrations.RunPython(migrate_processing_to_draft, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="historicalitem",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Draft"),
                    (2, "Available"),
                    (3, "Reserved"),
                    (4, "Rented"),
                    (5, "Sold"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Draft"),
                    (2, "Available"),
                    (3, "Reserved"),
                    (4, "Rented"),
                    (5, "Sold"),
                ],
                default=0,
            ),
        ),
    ]
