# Generated by Django 6.0.3 on 2026-03-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_remove_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='publish_notification_sent',
            field=models.BooleanField(default=False, editable=False, help_text='Set to True after the first publish notification has been sent.'),
        ),
        migrations.AddField(
            model_name='item',
            name='publish_notification_sent',
            field=models.BooleanField(default=False, editable=False, help_text='Set to True after the first publish notification has been sent.'),
        ),
    ]
