# Generated by Django 6.0.4 on 2026-04-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0012_add_publish_notification_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalitem",
            name="ap_id",
            field=models.URLField(
                blank=True,
                default="",
                editable=False,
                help_text="ActivityPub object URI for this item.",
                max_length=2048,
            ),
        ),
        migrations.AddField(
            model_name="historicalitem",
            name="federation_visibility",
            field=models.CharField(
                choices=[
                    ("public_federated", "Public (federated)"),
                    ("local_only", "Local only"),
                ],
                default="local_only",
                help_text="Controls whether this item is shared via ActivityPub federation. 'Public (federated)' shares it with allowed peer instances. 'Local only' keeps it on this instance only.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="ap_id",
            field=models.URLField(
                blank=True,
                default="",
                editable=False,
                help_text="ActivityPub object URI for this item.",
                max_length=2048,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="federation_visibility",
            field=models.CharField(
                choices=[
                    ("public_federated", "Public (federated)"),
                    ("local_only", "Local only"),
                ],
                default="local_only",
                help_text="Controls whether this item is shared via ActivityPub federation. 'Public (federated)' shares it with allowed peer instances. 'Local only' keeps it on this instance only.",
                max_length=20,
            ),
        ),
    ]
