# Generated by Django 6.0.6 on 2026-07-06 12:47

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0016_item_items_status_created_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalitem",
            name="price",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                help_text="Price for sell/rent items (must be > 0). Leave blank for donate/borrow items. Rental price per rental_period (when sales type is rent).",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalitem",
            name="rental_period",
            field=models.CharField(
                blank=True,
                choices=[("h", "Hourly"), ("d", "Daily"), ("w", "Weekly")],
                default="h",
                help_text="Defines the period the rental price applies to (hourly, daily, weekly). Used for price calculation and display formatting.",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                help_text="Price for sell/rent items (must be > 0). Leave blank for donate/borrow items. Rental price per rental_period (when sales type is rent).",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="rental_period",
            field=models.CharField(
                blank=True,
                choices=[("h", "Hourly"), ("d", "Daily"), ("w", "Weekly")],
                default="h",
                help_text="Defines the period the rental price applies to (hourly, daily, weekly). Used for price calculation and display formatting.",
                max_length=1,
            ),
        ),
    ]
