# Generated by Django 6.0.5 on 2026-07-07 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('items', '0017_alter_historicalitem_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemgroupobjectpermission',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='itemuserobjectpermission',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='itemgroupobjectpermission',
            index=models.Index(fields=['group', 'content_object'], name='items_itemg_group_i_c29689_idx'),
        ),
        migrations.AddIndex(
            model_name='itemuserobjectpermission',
            index=models.Index(fields=['user', 'content_object'], name='items_itemu_user_id_a364a8_idx'),
        ),
    ]
