# Generated by Django 6.0.6 on 2026-08-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0018_add_performance_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalitem",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Draft"),
                    (2, "Available"),
                    (3, "Reserved"),
                    (4, "Rented"),
                    (5, "Sold"),
                    (6, "Archived"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Draft"),
                    (2, "Available"),
                    (3, "Reserved"),
                    (4, "Rented"),
                    (5, "Sold"),
                    (6, "Archived"),
                ],
                default=0,
            ),
        ),
    ]
