# Generated by Django 6.1 on 2026-09-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0020_search_extensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalitem",
            name="ledger_beneficiary",
            field=models.CharField(
                choices=[("owner", "Owner"), ("community", "Community")],
                default="owner",
                help_text="Owner: booking charges credit the owner. Community: the community owns the item and its charges go to the community; the owner looks after it. Set by the treasurer.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="ledger_beneficiary",
            field=models.CharField(
                choices=[("owner", "Owner"), ("community", "Community")],
                default="owner",
                help_text="Owner: booking charges credit the owner. Community: the community owns the item and its charges go to the community; the owner looks after it. Set by the treasurer.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalitem",
            name="payment_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Charge bookings of this item through the community ledger. Without it, bookings never post a charge, whatever the price.",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="payment_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Charge bookings of this item through the community ledger. Without it, bookings never post a charge, whatever the price.",
            ),
        ),
    ]
