# Generated by Django 6.0.6 on 2026-08-18 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0020_search_extensions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalitem",
            name="price_unit",
            field=models.CharField(
                choices=[("money", "Money"), ("coin", "Community coins")],
                default="money",
                help_text="What ``price`` is denominated in: the default currency, or community coins. Meaningless (and forced back to money) when price is left blank.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="price_unit",
            field=models.CharField(
                choices=[("money", "Money"), ("coin", "Community coins")],
                default="money",
                help_text="What ``price`` is denominated in: the default currency, or community coins. Meaningless (and forced back to money) when price is left blank.",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("price__isnull", False), ("price_unit", "money"), _connector="OR"
                ),
                name="items_price_unit_money_when_no_price",
            ),
        ),
    ]
