# Generated by Django 6.0.4 on 2026-04-30 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0004_booking_exclude_overlapping_confirmed_bookings_with_time_to_and_more",
        ),
        ("federation", "0001_initial"),
        ("items", "0013_historicalitem_ap_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="ap_id",
            field=models.URLField(
                blank=True,
                default="",
                editable=False,
                help_text="ActivityPub object URI for this booking.",
                max_length=2048,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="remote_booker_actor",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when the booker is a remote federated actor.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="federation.remoteactor",
            ),
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="ap_id",
            field=models.URLField(
                blank=True,
                default="",
                editable=False,
                help_text="ActivityPub object URI for this booking.",
                max_length=2048,
            ),
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="remote_booker_actor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Set when the booker is a remote federated actor.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="federation.remoteactor",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="ap_id",
            field=models.URLField(
                blank=True,
                default="",
                editable=False,
                help_text="ActivityPub object URI for this message.",
                max_length=2048,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="remote_sender_actor",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when the message sender is a remote federated actor.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_messages",
                to="federation.remoteactor",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Local user who made this booking. Null when booker is a remote actor.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbooking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Local user who made this booking. Null when booker is a remote actor.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                help_text="Local sender. Null when sender is a remote actor.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("remote_booker_actor__isnull", True), ("user__isnull", False)
                    ),
                    models.Q(
                        ("remote_booker_actor__isnull", False), ("user__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="booking_booker_xor",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("remote_sender_actor__isnull", True), ("sender__isnull", False)
                    ),
                    models.Q(
                        ("remote_sender_actor__isnull", False), ("sender__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="message_sender_xor",
            ),
        ),
    ]
