# Generated by Django 6.0.5 on 2026-07-07 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_ap_id_booking_remote_booker_actor_and_more'),
        ('federation', '0003_allow_null_raw_jsonld_remote_item'),
        ('items', '0017_alter_historicalitem_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='bookings_bo_user_id_69a5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['item', 'status'], name='bookings_bo_item_id_f8180d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['booking', 'is_read'], name='bookings_me_booking_b0a934_idx'),
        ),
    ]
