# Generated by Django 6.0.6 on 2026-06-28 20:02

import django.contrib.postgres.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_add_performance_indexes"),
        ("federation", "0003_allow_null_raw_jsonld_remote_item"),
        ("items", "0013_historicalitem_ap_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="exclude_overlapping_confirmed_bookings_with_time_to",
        ),
        migrations.RemoveConstraint(
            model_name="booking",
            name="exclude_overlapping_confirmed_bookings_without_time_to",
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Pending"),
                    (2, "Cancelled"),
                    (3, "Confirmed"),
                    (4, "Completed"),
                    (5, "Rejected"),
                    (6, "In Progress"),
                ],
                default=1,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbooking",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Pending"),
                    (2, "Cancelled"),
                    (3, "Confirmed"),
                    (4, "Completed"),
                    (5, "Rejected"),
                    (6, "In Progress"),
                ],
                default=1,
                verbose_name="Status",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("status__in", [3, 6]), ("time_to__isnull", False)),
                expressions=[
                    (
                        models.Func(
                            models.F("time_from"),
                            models.F("time_to"),
                            function="tstzrange",
                        ),
                        "&&",
                    ),
                    (models.F("item"), "="),
                ],
                name="exclude_overlapping_confirmed_bookings_with_time_to",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("status__in", [3, 6]), ("time_to__isnull", True)),
                expressions=[(models.F("item"), "=")],
                name="exclude_overlapping_confirmed_bookings_without_time_to",
            ),
        ),
    ]
