# Generated by Django 6.1 on 2026-09-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_ledger_booking_charges"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="sale_reminders_sent",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Daily reminders sent to the buyer of an accepted sale (ledger plan D19).",
            ),
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="sale_reminders_sent",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Daily reminders sent to the buyer of an accepted sale (ledger plan D19).",
            ),
        ),
    ]
