// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:9000' | (string & {});
};

/**
 * * `item_added` - Item added
 * * `item_removed` - Item removed
 */
export type ActionEnum = 'item_added' | 'item_removed';

export type AuthToken = {
    /**
     * Anmeldename
     */
    username: string;
    /**
     * Passwort
     */
    password: string;
    readonly token: string;
};

export type BlankEnum = '';

/**
 * Full serializer for Book detail view.
 *
 * Read-side: exposes isbn, language, year, topic, metadata, authors,
 * genres, verlag (publisher name), shelf from Item.properties.
 *
 * Write-side: accepts authors (list of strings), genres (list of strings),
 * publisher (string), shelf (string), isbn, language, year, topic,
 * metadata.  The old UUID-based author_ids / genre_ids / verlag_id /
 * shelf_id fields are no longer accepted.
 */
export type Book = {
    readonly id: string;
    readonly images: Array<Image>;
    readonly user: string;
    readonly first_image: string;
    price?: string | null;
    readonly co_owners: string;
    readonly isbn: string;
    readonly language: string;
    readonly year: string;
    readonly topic: string;
    readonly metadata: string;
    readonly authors: string;
    readonly genres: string;
    readonly verlag: string;
    readonly shelf: string;
    /**
     * Category of the item
     *
     * * `books` - Bücher
     * * `clothing` - Kleidung
     * * `electronics` - Elektronik
     * * `furniture` - Möbel
     * * `garden` - Garten
     * * `kitchen` - Küche
     * * `other` - Andere
     * * `rooms` - Räume
     * * `sports` - Sport
     * * `tools` - Werkzeuge
     * * `toys` - Spielzeug
     * * `vehicles` - Fahrzeuge
     */
    category?: CategoryEnum | BlankEnum;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Interner Artikel, nicht für öffentliche Anzeige
     */
    internal?: boolean;
    /**
     * Kontaktinformationen öffentlich anzeigen
     */
    display_contact?: boolean;
    /**
     * How the item is offered: Sell, Donate, Rent, Borrow, Want to Buy, or Want to Rent.
     *
     * * `sell` - Sell
     * * `donate` - Donate
     * * `rent` - Rent
     * * `borrow` - Ausleihen
     * * `want_buy` - Want to Buy
     * * `want_rent` - Want to Rent
     */
    sales_type: SalesTypeEnum;
    readonly price_currency: string | null;
    /**
     * Only used for formatting, price must always be per hour for rental items
     *
     * * `h` - Stündlich
     * * `d` - Täglich
     * * `w` - Wöchentlich
     */
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Selbstbedienungsvermietung ohne Zustimmung des Eigentümers erlauben
     */
    rental_self_service?: boolean;
    /**
     * Unbefristete Vermietungen ohne Rückgabedatum erlauben
     */
    rental_open_end?: boolean;
    /**
     * Zahlung über internes Zahlungssystem aktivieren
     */
    payment_enabled?: boolean;
    readonly created_at: string;
    readonly updated_at: string;
    /**
     * Condition of the item
     *
     * * `0` - Neu
     * * `1` - Gebraucht
     * * `2` - Kaputt
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status873Enum;
    /**
     * Set to True after the first publish notification has been sent.
     */
    readonly publish_notification_sent: boolean;
    /**
     * Who can see this item: Public (everyone), Authenticated (logged-in users), Specific (selected users/groups), or Private (owner and co-owners only).
     *
     * * `0` - Öffentlich
     * * `1` - Authenticated
     * * `2` - Specific
     * * `3` - Private
     */
    visibility?: VisibilityEnum;
    /**
     * Category-specific properties stored as JSONB. For books: isbn, language, year, topic, metadata, authors, genres, publisher, shelf.
     */
    properties?: unknown;
};

/**
 * Lightweight serializer for Book list view.
 */
export type BookList = {
    readonly id: string;
    readonly user: string;
    readonly first_image: string;
    price?: string | null;
    readonly isbn: string;
    readonly language: string;
    readonly year: string;
    readonly topic: string;
    readonly authors: string;
    readonly genres: string;
    readonly verlag_name: string;
    readonly shelf_name: string;
    /**
     * Category of the item
     *
     * * `books` - Bücher
     * * `clothing` - Kleidung
     * * `electronics` - Elektronik
     * * `furniture` - Möbel
     * * `garden` - Garten
     * * `kitchen` - Küche
     * * `other` - Andere
     * * `rooms` - Räume
     * * `sports` - Sport
     * * `tools` - Werkzeuge
     * * `toys` - Spielzeug
     * * `vehicles` - Fahrzeuge
     */
    category?: CategoryEnum | BlankEnum;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Interner Artikel, nicht für öffentliche Anzeige
     */
    internal?: boolean;
    /**
     * Kontaktinformationen öffentlich anzeigen
     */
    display_contact?: boolean;
    /**
     * How the item is offered: Sell, Donate, Rent, Borrow, Want to Buy, or Want to Rent.
     *
     * * `sell` - Sell
     * * `donate` - Donate
     * * `rent` - Rent
     * * `borrow` - Ausleihen
     * * `want_buy` - Want to Buy
     * * `want_rent` - Want to Rent
     */
    sales_type: SalesTypeEnum;
    readonly price_currency: string | null;
    /**
     * Only used for formatting, price must always be per hour for rental items
     *
     * * `h` - Stündlich
     * * `d` - Täglich
     * * `w` - Wöchentlich
     */
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Selbstbedienungsvermietung ohne Zustimmung des Eigentümers erlauben
     */
    rental_self_service?: boolean;
    /**
     * Unbefristete Vermietungen ohne Rückgabedatum erlauben
     */
    rental_open_end?: boolean;
    /**
     * Zahlung über internes Zahlungssystem aktivieren
     */
    payment_enabled?: boolean;
    readonly created_at: string;
    readonly updated_at: string;
    /**
     * Condition of the item
     *
     * * `0` - Neu
     * * `1` - Gebraucht
     * * `2` - Kaputt
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status873Enum;
    /**
     * Set to True after the first publish notification has been sent.
     */
    readonly publish_notification_sent: boolean;
    /**
     * Who can see this item: Public (everyone), Authenticated (logged-in users), Specific (selected users/groups), or Private (owner and co-owners only).
     *
     * * `0` - Öffentlich
     * * `1` - Authenticated
     * * `2` - Specific
     * * `3` - Private
     */
    visibility?: VisibilityEnum;
    /**
     * Category-specific properties stored as JSONB. For books: isbn, language, year, topic, metadata, authors, genres, publisher, shelf.
     */
    properties?: unknown;
};

/**
 * Detailed serializer for Booking where `item` is represented only by UUID.
 */
export type Booking = {
    readonly id: string;
    status?: Status164Enum;
    item: string;
    item_details: ItemMinimal;
    user: User;
    /**
     * Von
     */
    time_from?: string | null;
    /**
     * Bis
     */
    time_to?: string | null;
    /**
     * Angebot
     *
     * Angebotener Preis für die Buchung
     */
    offer?: string | null;
    /**
     * Gegenangebot
     *
     * Gegenangebotspreis für die Buchung
     */
    counter_offer?: string | null;
    accepted_by?: string | null;
    readonly created_at: string;
    readonly updated_at: string;
    /**
     * Return unread_messages_count if it exists as an annotated field.
     */
    readonly unread_messages_count: number | null;
};

/**
 * Detailed serializer for Booking where `item` is represented only by UUID.
 */
export type BookingList = {
    readonly id: string;
    status?: Status164Enum;
    readonly item: string;
    item_details: ItemMinimal;
    user: User;
    readonly created_at: string;
    /**
     * Von
     */
    time_from?: string | null;
    /**
     * Bis
     */
    time_to?: string | null;
    /**
     * Return unread_messages_count if it exists as an annotated field.
     */
    readonly unread_messages_count: number | null;
};

/**
 * * `books` - Bücher
 * * `clothing` - Kleidung
 * * `electronics` - Elektronik
 * * `furniture` - Möbel
 * * `garden` - Garten
 * * `kitchen` - Küche
 * * `other` - Andere
 * * `rooms` - Räume
 * * `sports` - Sport
 * * `tools` - Werkzeuge
 * * `toys` - Spielzeug
 * * `vehicles` - Fahrzeuge
 */
export type CategoryEnum = 'books' | 'clothing' | 'electronics' | 'furniture' | 'garden' | 'kitchen' | 'other' | 'rooms' | 'sports' | 'tools' | 'toys' | 'vehicles';

/**
 * Serializer for Collection model.
 */
export type Collection = {
    readonly id: string;
    name: string;
    description?: string;
    readonly owner: string;
    readonly items_count: string;
    readonly can_remove_items: string;
    readonly collection_items: Array<CollectionItem>;
    readonly created_at: string;
    readonly updated_at: string;
};

/**
 * Read-only serializer for CollectionEvent audit log entries.
 */
export type CollectionEvent = {
    readonly id: string;
    readonly item_id: string;
    /**
     * Snapshot of item name at event time
     */
    readonly item_name: string;
    readonly actor: string;
    action: ActionEnum;
    readonly timestamp: string;
};

/**
 * Read-only serializer for a single aggregated permission grant on a collection.
 *
 * Expects pre-aggregated dicts with keys:
 * subject_type, subject_id, subject_name, role
 */
export type CollectionGrant = {
    subject_type: string;
    subject_id: string;
    subject_name: string;
    permission: string;
};

/**
 * Serializer for CollectionItem model.
 */
export type CollectionItem = {
    readonly id: string;
    collection: string;
    item: ItemMinimal;
    readonly added_at: string;
    readonly added_by: string;
    /**
     * Optional note about this item
     */
    note?: string;
    ordering?: number;
};

/**
 * Lightweight serializer for collection lists.
 */
export type CollectionList = {
    readonly id: string;
    name: string;
    description?: string;
    readonly owner: string;
    readonly items_count: string;
    readonly can_add_items: string;
    readonly created_at: string;
    readonly updated_at: string;
};

/**
 * * `0` - Neu
 * * `1` - Gebraucht
 * * `2` - Kaputt
 */
export type ConditionEnum = 0 | 1 | 2;

/**
 * Serializer for auth Group model.
 */
export type Group = {
    readonly id: number;
    name: string;
};

/**
 * Serializer for Image model.
 */
export type Image = {
    readonly id: string;
    original: string;
    ordering?: number | null;
    readonly thumbnail: string;
    readonly preview: string;
    item: string;
};

/**
 * Serializer for Item model.
 */
export type Item = {
    readonly id: string;
    readonly images: Array<Image>;
    readonly user: string;
    readonly first_image: string;
    price?: string | null;
    readonly co_owners: string;
    /**
     * Category of the item
     *
     * * `books` - Bücher
     * * `clothing` - Kleidung
     * * `electronics` - Elektronik
     * * `furniture` - Möbel
     * * `garden` - Garten
     * * `kitchen` - Küche
     * * `other` - Andere
     * * `rooms` - Räume
     * * `sports` - Sport
     * * `tools` - Werkzeuge
     * * `toys` - Spielzeug
     * * `vehicles` - Fahrzeuge
     */
    category?: CategoryEnum | BlankEnum;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Interner Artikel, nicht für öffentliche Anzeige
     */
    internal?: boolean;
    /**
     * Kontaktinformationen öffentlich anzeigen
     */
    display_contact?: boolean;
    /**
     * How the item is offered: Sell, Donate, Rent, Borrow, Want to Buy, or Want to Rent.
     *
     * * `sell` - Sell
     * * `donate` - Donate
     * * `rent` - Rent
     * * `borrow` - Ausleihen
     * * `want_buy` - Want to Buy
     * * `want_rent` - Want to Rent
     */
    sales_type: SalesTypeEnum;
    readonly price_currency: string | null;
    /**
     * Only used for formatting, price must always be per hour for rental items
     *
     * * `h` - Stündlich
     * * `d` - Täglich
     * * `w` - Wöchentlich
     */
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Selbstbedienungsvermietung ohne Zustimmung des Eigentümers erlauben
     */
    rental_self_service?: boolean;
    /**
     * Unbefristete Vermietungen ohne Rückgabedatum erlauben
     */
    rental_open_end?: boolean;
    /**
     * Zahlung über internes Zahlungssystem aktivieren
     */
    payment_enabled?: boolean;
    readonly created_at: string;
    readonly updated_at: string;
    /**
     * Condition of the item
     *
     * * `0` - Neu
     * * `1` - Gebraucht
     * * `2` - Kaputt
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status873Enum;
    /**
     * Set to True after the first publish notification has been sent.
     */
    readonly publish_notification_sent: boolean;
    /**
     * Who can see this item: Public (everyone), Authenticated (logged-in users), Specific (selected users/groups), or Private (owner and co-owners only).
     *
     * * `0` - Öffentlich
     * * `1` - Authenticated
     * * `2` - Specific
     * * `3` - Private
     */
    visibility?: VisibilityEnum;
    /**
     * Category-specific properties stored as JSONB. For books: isbn, language, year, topic, metadata, authors, genres, publisher, shelf.
     */
    properties?: unknown;
};

/**
 * Lightweight serializer for item lists.
 */
export type ItemList = {
    readonly id: string;
    readonly user: string;
    readonly first_image: string;
    price?: string | null;
    /**
     * Category of the item
     *
     * * `books` - Bücher
     * * `clothing` - Kleidung
     * * `electronics` - Elektronik
     * * `furniture` - Möbel
     * * `garden` - Garten
     * * `kitchen` - Küche
     * * `other` - Andere
     * * `rooms` - Räume
     * * `sports` - Sport
     * * `tools` - Werkzeuge
     * * `toys` - Spielzeug
     * * `vehicles` - Fahrzeuge
     */
    category?: CategoryEnum | BlankEnum;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Interner Artikel, nicht für öffentliche Anzeige
     */
    internal?: boolean;
    /**
     * Kontaktinformationen öffentlich anzeigen
     */
    display_contact?: boolean;
    /**
     * How the item is offered: Sell, Donate, Rent, Borrow, Want to Buy, or Want to Rent.
     *
     * * `sell` - Sell
     * * `donate` - Donate
     * * `rent` - Rent
     * * `borrow` - Ausleihen
     * * `want_buy` - Want to Buy
     * * `want_rent` - Want to Rent
     */
    sales_type: SalesTypeEnum;
    readonly price_currency: string | null;
    /**
     * Only used for formatting, price must always be per hour for rental items
     *
     * * `h` - Stündlich
     * * `d` - Täglich
     * * `w` - Wöchentlich
     */
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Selbstbedienungsvermietung ohne Zustimmung des Eigentümers erlauben
     */
    rental_self_service?: boolean;
    /**
     * Unbefristete Vermietungen ohne Rückgabedatum erlauben
     */
    rental_open_end?: boolean;
    /**
     * Zahlung über internes Zahlungssystem aktivieren
     */
    payment_enabled?: boolean;
    readonly created_at: string;
    readonly updated_at: string;
    /**
     * Condition of the item
     *
     * * `0` - Neu
     * * `1` - Gebraucht
     * * `2` - Kaputt
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status873Enum;
    /**
     * Set to True after the first publish notification has been sent.
     */
    readonly publish_notification_sent: boolean;
    /**
     * Who can see this item: Public (everyone), Authenticated (logged-in users), Specific (selected users/groups), or Private (owner and co-owners only).
     *
     * * `0` - Öffentlich
     * * `1` - Authenticated
     * * `2` - Specific
     * * `3` - Private
     */
    visibility?: VisibilityEnum;
    /**
     * Category-specific properties stored as JSONB. For books: isbn, language, year, topic, metadata, authors, genres, publisher, shelf.
     */
    properties?: unknown;
};

/**
 * Lightweight serializer for item lists.
 */
export type ItemMinimal = {
    readonly id: string;
    name?: string;
    readonly first_image: string;
    /**
     * How the item is offered: Sell, Donate, Rent, Borrow, Want to Buy, or Want to Rent.
     *
     * * `sell` - Sell
     * * `donate` - Donate
     * * `rent` - Rent
     * * `borrow` - Ausleihen
     * * `want_buy` - Want to Buy
     * * `want_rent` - Want to Rent
     */
    sales_type: SalesTypeEnum;
    price?: string | null;
    readonly price_currency: string | null;
};

/**
 * * `en` - Englisch
 * * `de` - Deutsch
 */
export type LanguageEnum = 'en' | 'de';

/**
 * Serializer for Message model. Booking is referenced by UUID.
 */
export type Message = {
    readonly id: string;
    booking: string;
    readonly sender: string;
    readonly created_at: string;
    message: string;
    is_read?: boolean;
};

/**
 * Flat serializer for GET/PATCH /api/notification-preferences/me/.
 *
 * Keys are <provider_type>_<event_type> booleans.
 * Currently: rocketchat_new_message.
 */
export type NotificationPreferenceMe = {
    rocketchat_new_message?: boolean;
};

export type PaginatedBookListList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<BookList>;
};

export type PaginatedBookingListList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<BookingList>;
};

export type PaginatedCollectionEventList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<CollectionEvent>;
};

export type PaginatedCollectionGrantList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<CollectionGrant>;
};

export type PaginatedCollectionItemList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<CollectionItem>;
};

export type PaginatedCollectionListList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<CollectionList>;
};

export type PaginatedGroupList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Group>;
};

export type PaginatedImageList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Image>;
};

export type PaginatedItemListList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<ItemList>;
};

export type PaginatedMessageList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Message>;
};

export type PaginatedProfileList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Profile>;
};

export type PaginatedUserList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<User>;
};

/**
 * Full serializer for Book detail view.
 *
 * Read-side: exposes isbn, language, year, topic, metadata, authors,
 * genres, verlag (publisher name), shelf from Item.properties.
 *
 * Write-side: accepts authors (list of strings), genres (list of strings),
 * publisher (string), shelf (string), isbn, language, year, topic,
 * metadata.  The old UUID-based author_ids / genre_ids / verlag_id /
 * shelf_id fields are no longer accepted.
 */
export type PatchedBook = {
    readonly id?: string;
    readonly images?: Array<Image>;
    readonly user?: string;
    readonly first_image?: string;
    price?: string | null;
    readonly co_owners?: string;
    readonly isbn?: string;
    readonly language?: string;
    readonly year?: string;
    readonly topic?: string;
    readonly metadata?: string;
    readonly authors?: string;
    readonly genres?: string;
    readonly verlag?: string;
    readonly shelf?: string;
    /**
     * Category of the item
     *
     * * `books` - Bücher
     * * `clothing` - Kleidung
     * * `electronics` - Elektronik
     * * `furniture` - Möbel
     * * `garden` - Garten
     * * `kitchen` - Küche
     * * `other` - Andere
     * * `rooms` - Räume
     * * `sports` - Sport
     * * `tools` - Werkzeuge
     * * `toys` - Spielzeug
     * * `vehicles` - Fahrzeuge
     */
    category?: CategoryEnum | BlankEnum;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Interner Artikel, nicht für öffentliche Anzeige
     */
    internal?: boolean;
    /**
     * Kontaktinformationen öffentlich anzeigen
     */
    display_contact?: boolean;
    /**
     * How the item is offered: Sell, Donate, Rent, Borrow, Want to Buy, or Want to Rent.
     *
     * * `sell` - Sell
     * * `donate` - Donate
     * * `rent` - Rent
     * * `borrow` - Ausleihen
     * * `want_buy` - Want to Buy
     * * `want_rent` - Want to Rent
     */
    sales_type?: SalesTypeEnum;
    readonly price_currency?: string | null;
    /**
     * Only used for formatting, price must always be per hour for rental items
     *
     * * `h` - Stündlich
     * * `d` - Täglich
     * * `w` - Wöchentlich
     */
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Selbstbedienungsvermietung ohne Zustimmung des Eigentümers erlauben
     */
    rental_self_service?: boolean;
    /**
     * Unbefristete Vermietungen ohne Rückgabedatum erlauben
     */
    rental_open_end?: boolean;
    /**
     * Zahlung über internes Zahlungssystem aktivieren
     */
    payment_enabled?: boolean;
    readonly created_at?: string;
    readonly updated_at?: string;
    /**
     * Condition of the item
     *
     * * `0` - Neu
     * * `1` - Gebraucht
     * * `2` - Kaputt
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status873Enum;
    /**
     * Set to True after the first publish notification has been sent.
     */
    readonly publish_notification_sent?: boolean;
    /**
     * Who can see this item: Public (everyone), Authenticated (logged-in users), Specific (selected users/groups), or Private (owner and co-owners only).
     *
     * * `0` - Öffentlich
     * * `1` - Authenticated
     * * `2` - Specific
     * * `3` - Private
     */
    visibility?: VisibilityEnum;
    /**
     * Category-specific properties stored as JSONB. For books: isbn, language, year, topic, metadata, authors, genres, publisher, shelf.
     */
    properties?: unknown;
};

/**
 * Detailed serializer for Booking where `item` is represented only by UUID.
 */
export type PatchedBooking = {
    readonly id?: string;
    status?: Status164Enum;
    item?: string;
    item_details?: ItemMinimal;
    user?: User;
    /**
     * Von
     */
    time_from?: string | null;
    /**
     * Bis
     */
    time_to?: string | null;
    /**
     * Angebot
     *
     * Angebotener Preis für die Buchung
     */
    offer?: string | null;
    /**
     * Gegenangebot
     *
     * Gegenangebotspreis für die Buchung
     */
    counter_offer?: string | null;
    accepted_by?: string | null;
    readonly created_at?: string;
    readonly updated_at?: string;
    /**
     * Return unread_messages_count if it exists as an annotated field.
     */
    readonly unread_messages_count?: number | null;
};

/**
 * Serializer for Collection model.
 */
export type PatchedCollection = {
    readonly id?: string;
    name?: string;
    description?: string;
    readonly owner?: string;
    readonly items_count?: string;
    readonly can_remove_items?: string;
    readonly collection_items?: Array<CollectionItem>;
    readonly created_at?: string;
    readonly updated_at?: string;
};

/**
 * Serializer for CollectionItem model.
 */
export type PatchedCollectionItem = {
    readonly id?: string;
    collection?: string;
    item?: ItemMinimal;
    readonly added_at?: string;
    readonly added_by?: string;
    /**
     * Optional note about this item
     */
    note?: string;
    ordering?: number;
};

/**
 * Serializer for Image model.
 */
export type PatchedImage = {
    readonly id?: string;
    original?: string;
    ordering?: number | null;
    readonly thumbnail?: string;
    readonly preview?: string;
    item?: string;
};

/**
 * Serializer for Item model.
 */
export type PatchedItem = {
    readonly id?: string;
    readonly images?: Array<Image>;
    readonly user?: string;
    readonly first_image?: string;
    price?: string | null;
    readonly co_owners?: string;
    /**
     * Category of the item
     *
     * * `books` - Bücher
     * * `clothing` - Kleidung
     * * `electronics` - Elektronik
     * * `furniture` - Möbel
     * * `garden` - Garten
     * * `kitchen` - Küche
     * * `other` - Andere
     * * `rooms` - Räume
     * * `sports` - Sport
     * * `tools` - Werkzeuge
     * * `toys` - Spielzeug
     * * `vehicles` - Fahrzeuge
     */
    category?: CategoryEnum | BlankEnum;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Interner Artikel, nicht für öffentliche Anzeige
     */
    internal?: boolean;
    /**
     * Kontaktinformationen öffentlich anzeigen
     */
    display_contact?: boolean;
    /**
     * How the item is offered: Sell, Donate, Rent, Borrow, Want to Buy, or Want to Rent.
     *
     * * `sell` - Sell
     * * `donate` - Donate
     * * `rent` - Rent
     * * `borrow` - Ausleihen
     * * `want_buy` - Want to Buy
     * * `want_rent` - Want to Rent
     */
    sales_type?: SalesTypeEnum;
    readonly price_currency?: string | null;
    /**
     * Only used for formatting, price must always be per hour for rental items
     *
     * * `h` - Stündlich
     * * `d` - Täglich
     * * `w` - Wöchentlich
     */
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Selbstbedienungsvermietung ohne Zustimmung des Eigentümers erlauben
     */
    rental_self_service?: boolean;
    /**
     * Unbefristete Vermietungen ohne Rückgabedatum erlauben
     */
    rental_open_end?: boolean;
    /**
     * Zahlung über internes Zahlungssystem aktivieren
     */
    payment_enabled?: boolean;
    readonly created_at?: string;
    readonly updated_at?: string;
    /**
     * Condition of the item
     *
     * * `0` - Neu
     * * `1` - Gebraucht
     * * `2` - Kaputt
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status873Enum;
    /**
     * Set to True after the first publish notification has been sent.
     */
    readonly publish_notification_sent?: boolean;
    /**
     * Who can see this item: Public (everyone), Authenticated (logged-in users), Specific (selected users/groups), or Private (owner and co-owners only).
     *
     * * `0` - Öffentlich
     * * `1` - Authenticated
     * * `2` - Specific
     * * `3` - Private
     */
    visibility?: VisibilityEnum;
    /**
     * Category-specific properties stored as JSONB. For books: isbn, language, year, topic, metadata, authors, genres, publisher, shelf.
     */
    properties?: unknown;
};

/**
 * Serializer for Message model. Booking is referenced by UUID.
 */
export type PatchedMessage = {
    readonly id?: string;
    booking?: string;
    readonly sender?: string;
    readonly created_at?: string;
    message?: string;
    is_read?: boolean;
};

/**
 * Flat serializer for GET/PATCH /api/notification-preferences/me/.
 *
 * Keys are <provider_type>_<event_type> booleans.
 * Currently: rocketchat_new_message.
 */
export type PatchedNotificationPreferenceMe = {
    rocketchat_new_message?: boolean;
};

export type PatchedProfile = {
    readonly username?: string;
    name?: string;
    readonly email?: string;
    phone?: string;
    bio?: string;
    address?: string;
    email_reminder?: boolean;
    profile_image?: string | null;
    /**
     * Preferred language
     *
     * UI language preference for this user.
     *
     * * `en` - Englisch
     * * `de` - Deutsch
     */
    language?: LanguageEnum | BlankEnum;
};

export type PatchedUser = {
    readonly id?: string;
    /**
     * Benutzername
     *
     * Erforderlich. 150 Zeichen oder weniger. Nur Buchstaben, Ziffern und @/./+/-/_.
     */
    username?: string;
    /**
     * Name des Benutzers
     */
    name?: string;
    /**
     * E-Mail-Adresse
     */
    email?: string;
};

export type Profile = {
    readonly username: string;
    name?: string;
    readonly email: string;
    phone?: string;
    bio?: string;
    address?: string;
    email_reminder?: boolean;
    profile_image?: string | null;
    /**
     * Preferred language
     *
     * UI language preference for this user.
     *
     * * `en` - Englisch
     * * `de` - Deutsch
     */
    language?: LanguageEnum | BlankEnum;
};

/**
 * * `h` - Stündlich
 * * `d` - Täglich
 * * `w` - Wöchentlich
 */
export type RentalPeriodEnum = 'h' | 'd' | 'w';

/**
 * * `sell` - Sell
 * * `donate` - Donate
 * * `rent` - Rent
 * * `borrow` - Ausleihen
 * * `want_buy` - Want to Buy
 * * `want_rent` - Want to Rent
 */
export type SalesTypeEnum = 'sell' | 'donate' | 'rent' | 'borrow' | 'want_buy' | 'want_rent';

/**
 * * `1` - Ausstehend
 * * `2` - Abgebrochen
 * * `3` - Bestätigt
 * * `4` - Abgeschlossen
 * * `5` - Abgelehnt
 */
export type Status164Enum = 1 | 2 | 3 | 4 | 5;

/**
 * * `0` - Entwurf
 * * `2` - Verfügbar
 * * `3` - Reserviert
 * * `4` - Rented
 * * `5` - Verkauft
 */
export type Status873Enum = 0 | 2 | 3 | 4 | 5;

export type User = {
    readonly id: string;
    /**
     * Benutzername
     *
     * Erforderlich. 150 Zeichen oder weniger. Nur Buchstaben, Ziffern und @/./+/-/_.
     */
    username: string;
    /**
     * Name des Benutzers
     */
    name?: string;
    /**
     * E-Mail-Adresse
     */
    email?: string;
};

/**
 * * `0` - Öffentlich
 * * `1` - Authenticated
 * * `2` - Specific
 * * `3` - Private
 */
export type VisibilityEnum = 0 | 1 | 2 | 3;

/**
 * Full serializer for Book detail view.
 *
 * Read-side: exposes isbn, language, year, topic, metadata, authors,
 * genres, verlag (publisher name), shelf from Item.properties.
 *
 * Write-side: accepts authors (list of strings), genres (list of strings),
 * publisher (string), shelf (string), isbn, language, year, topic,
 * metadata.  The old UUID-based author_ids / genre_ids / verlag_id /
 * shelf_id fields are no longer accepted.
 */
export type BookWritable = {
    price?: string | null;
    isbn_write?: string;
    language_write?: string;
    year_write?: number | null;
    topic_write?: string;
    metadata_write?: unknown;
    authors_write?: Array<string>;
    genres_write?: Array<string>;
    publisher?: string;
    shelf_write?: string;
    /**
     * Category of the item
     *
     * * `books` - Bücher
     * * `clothing` - Kleidung
     * * `electronics` - Elektronik
     * * `furniture` - Möbel
     * * `garden` - Garten
     * * `kitchen` - Küche
     * * `other` - Andere
     * * `rooms` - Räume
     * * `sports` - Sport
     * * `tools` - Werkzeuge
     * * `toys` - Spielzeug
     * * `vehicles` - Fahrzeuge
     */
    category?: CategoryEnum | BlankEnum;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Interner Artikel, nicht für öffentliche Anzeige
     */
    internal?: boolean;
    /**
     * Kontaktinformationen öffentlich anzeigen
     */
    display_contact?: boolean;
    /**
     * How the item is offered: Sell, Donate, Rent, Borrow, Want to Buy, or Want to Rent.
     *
     * * `sell` - Sell
     * * `donate` - Donate
     * * `rent` - Rent
     * * `borrow` - Ausleihen
     * * `want_buy` - Want to Buy
     * * `want_rent` - Want to Rent
     */
    sales_type: SalesTypeEnum;
    /**
     * Only used for formatting, price must always be per hour for rental items
     *
     * * `h` - Stündlich
     * * `d` - Täglich
     * * `w` - Wöchentlich
     */
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Selbstbedienungsvermietung ohne Zustimmung des Eigentümers erlauben
     */
    rental_self_service?: boolean;
    /**
     * Unbefristete Vermietungen ohne Rückgabedatum erlauben
     */
    rental_open_end?: boolean;
    /**
     * Zahlung über internes Zahlungssystem aktivieren
     */
    payment_enabled?: boolean;
    /**
     * Condition of the item
     *
     * * `0` - Neu
     * * `1` - Gebraucht
     * * `2` - Kaputt
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status873Enum;
    /**
     * Who can see this item: Public (everyone), Authenticated (logged-in users), Specific (selected users/groups), or Private (owner and co-owners only).
     *
     * * `0` - Öffentlich
     * * `1` - Authenticated
     * * `2` - Specific
     * * `3` - Private
     */
    visibility?: VisibilityEnum;
    /**
     * Category-specific properties stored as JSONB. For books: isbn, language, year, topic, metadata, authors, genres, publisher, shelf.
     */
    properties?: unknown;
};

/**
 * Lightweight serializer for Book list view.
 */
export type BookListWritable = {
    price?: string | null;
    /**
     * Category of the item
     *
     * * `books` - Bücher
     * * `clothing` - Kleidung
     * * `electronics` - Elektronik
     * * `furniture` - Möbel
     * * `garden` - Garten
     * * `kitchen` - Küche
     * * `other` - Andere
     * * `rooms` - Räume
     * * `sports` - Sport
     * * `tools` - Werkzeuge
     * * `toys` - Spielzeug
     * * `vehicles` - Fahrzeuge
     */
    category?: CategoryEnum | BlankEnum;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Interner Artikel, nicht für öffentliche Anzeige
     */
    internal?: boolean;
    /**
     * Kontaktinformationen öffentlich anzeigen
     */
    display_contact?: boolean;
    /**
     * How the item is offered: Sell, Donate, Rent, Borrow, Want to Buy, or Want to Rent.
     *
     * * `sell` - Sell
     * * `donate` - Donate
     * * `rent` - Rent
     * * `borrow` - Ausleihen
     * * `want_buy` - Want to Buy
     * * `want_rent` - Want to Rent
     */
    sales_type: SalesTypeEnum;
    /**
     * Only used for formatting, price must always be per hour for rental items
     *
     * * `h` - Stündlich
     * * `d` - Täglich
     * * `w` - Wöchentlich
     */
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Selbstbedienungsvermietung ohne Zustimmung des Eigentümers erlauben
     */
    rental_self_service?: boolean;
    /**
     * Unbefristete Vermietungen ohne Rückgabedatum erlauben
     */
    rental_open_end?: boolean;
    /**
     * Zahlung über internes Zahlungssystem aktivieren
     */
    payment_enabled?: boolean;
    /**
     * Condition of the item
     *
     * * `0` - Neu
     * * `1` - Gebraucht
     * * `2` - Kaputt
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status873Enum;
    /**
     * Who can see this item: Public (everyone), Authenticated (logged-in users), Specific (selected users/groups), or Private (owner and co-owners only).
     *
     * * `0` - Öffentlich
     * * `1` - Authenticated
     * * `2` - Specific
     * * `3` - Private
     */
    visibility?: VisibilityEnum;
    /**
     * Category-specific properties stored as JSONB. For books: isbn, language, year, topic, metadata, authors, genres, publisher, shelf.
     */
    properties?: unknown;
};

/**
 * Detailed serializer for Booking where `item` is represented only by UUID.
 */
export type BookingWritable = {
    status?: Status164Enum;
    item: string;
    /**
     * Von
     */
    time_from?: string | null;
    /**
     * Bis
     */
    time_to?: string | null;
    /**
     * Angebot
     *
     * Angebotener Preis für die Buchung
     */
    offer?: string | null;
    /**
     * Gegenangebot
     *
     * Gegenangebotspreis für die Buchung
     */
    counter_offer?: string | null;
    accepted_by?: string | null;
};

/**
 * Detailed serializer for Booking where `item` is represented only by UUID.
 */
export type BookingListWritable = {
    status?: Status164Enum;
    /**
     * Von
     */
    time_from?: string | null;
    /**
     * Bis
     */
    time_to?: string | null;
};

/**
 * Serializer for Collection model.
 */
export type CollectionWritable = {
    name: string;
    description?: string;
};

/**
 * Serializer for CollectionItem model.
 */
export type CollectionItemWritable = {
    collection: string;
    item_id: string;
    /**
     * Optional note about this item
     */
    note?: string;
    ordering?: number;
};

/**
 * Lightweight serializer for collection lists.
 */
export type CollectionListWritable = {
    name: string;
    description?: string;
};

/**
 * Serializer for auth Group model.
 */
export type GroupWritable = {
    name: string;
};

/**
 * Serializer for Image model.
 */
export type ImageWritable = {
    original: string;
    ordering?: number | null;
    item: string;
};

/**
 * Serializer for Item model.
 */
export type ItemWritable = {
    price?: string | null;
    /**
     * Category of the item
     *
     * * `books` - Bücher
     * * `clothing` - Kleidung
     * * `electronics` - Elektronik
     * * `furniture` - Möbel
     * * `garden` - Garten
     * * `kitchen` - Küche
     * * `other` - Andere
     * * `rooms` - Räume
     * * `sports` - Sport
     * * `tools` - Werkzeuge
     * * `toys` - Spielzeug
     * * `vehicles` - Fahrzeuge
     */
    category?: CategoryEnum | BlankEnum;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Interner Artikel, nicht für öffentliche Anzeige
     */
    internal?: boolean;
    /**
     * Kontaktinformationen öffentlich anzeigen
     */
    display_contact?: boolean;
    /**
     * How the item is offered: Sell, Donate, Rent, Borrow, Want to Buy, or Want to Rent.
     *
     * * `sell` - Sell
     * * `donate` - Donate
     * * `rent` - Rent
     * * `borrow` - Ausleihen
     * * `want_buy` - Want to Buy
     * * `want_rent` - Want to Rent
     */
    sales_type: SalesTypeEnum;
    /**
     * Only used for formatting, price must always be per hour for rental items
     *
     * * `h` - Stündlich
     * * `d` - Täglich
     * * `w` - Wöchentlich
     */
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Selbstbedienungsvermietung ohne Zustimmung des Eigentümers erlauben
     */
    rental_self_service?: boolean;
    /**
     * Unbefristete Vermietungen ohne Rückgabedatum erlauben
     */
    rental_open_end?: boolean;
    /**
     * Zahlung über internes Zahlungssystem aktivieren
     */
    payment_enabled?: boolean;
    /**
     * Condition of the item
     *
     * * `0` - Neu
     * * `1` - Gebraucht
     * * `2` - Kaputt
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status873Enum;
    /**
     * Who can see this item: Public (everyone), Authenticated (logged-in users), Specific (selected users/groups), or Private (owner and co-owners only).
     *
     * * `0` - Öffentlich
     * * `1` - Authenticated
     * * `2` - Specific
     * * `3` - Private
     */
    visibility?: VisibilityEnum;
    /**
     * Category-specific properties stored as JSONB. For books: isbn, language, year, topic, metadata, authors, genres, publisher, shelf.
     */
    properties?: unknown;
};

/**
 * Lightweight serializer for item lists.
 */
export type ItemListWritable = {
    price?: string | null;
    /**
     * Category of the item
     *
     * * `books` - Bücher
     * * `clothing` - Kleidung
     * * `electronics` - Elektronik
     * * `furniture` - Möbel
     * * `garden` - Garten
     * * `kitchen` - Küche
     * * `other` - Andere
     * * `rooms` - Räume
     * * `sports` - Sport
     * * `tools` - Werkzeuge
     * * `toys` - Spielzeug
     * * `vehicles` - Fahrzeuge
     */
    category?: CategoryEnum | BlankEnum;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Interner Artikel, nicht für öffentliche Anzeige
     */
    internal?: boolean;
    /**
     * Kontaktinformationen öffentlich anzeigen
     */
    display_contact?: boolean;
    /**
     * How the item is offered: Sell, Donate, Rent, Borrow, Want to Buy, or Want to Rent.
     *
     * * `sell` - Sell
     * * `donate` - Donate
     * * `rent` - Rent
     * * `borrow` - Ausleihen
     * * `want_buy` - Want to Buy
     * * `want_rent` - Want to Rent
     */
    sales_type: SalesTypeEnum;
    /**
     * Only used for formatting, price must always be per hour for rental items
     *
     * * `h` - Stündlich
     * * `d` - Täglich
     * * `w` - Wöchentlich
     */
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Selbstbedienungsvermietung ohne Zustimmung des Eigentümers erlauben
     */
    rental_self_service?: boolean;
    /**
     * Unbefristete Vermietungen ohne Rückgabedatum erlauben
     */
    rental_open_end?: boolean;
    /**
     * Zahlung über internes Zahlungssystem aktivieren
     */
    payment_enabled?: boolean;
    /**
     * Condition of the item
     *
     * * `0` - Neu
     * * `1` - Gebraucht
     * * `2` - Kaputt
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status873Enum;
    /**
     * Who can see this item: Public (everyone), Authenticated (logged-in users), Specific (selected users/groups), or Private (owner and co-owners only).
     *
     * * `0` - Öffentlich
     * * `1` - Authenticated
     * * `2` - Specific
     * * `3` - Private
     */
    visibility?: VisibilityEnum;
    /**
     * Category-specific properties stored as JSONB. For books: isbn, language, year, topic, metadata, authors, genres, publisher, shelf.
     */
    properties?: unknown;
};

/**
 * Lightweight serializer for item lists.
 */
export type ItemMinimalWritable = {
    name?: string;
    /**
     * How the item is offered: Sell, Donate, Rent, Borrow, Want to Buy, or Want to Rent.
     *
     * * `sell` - Sell
     * * `donate` - Donate
     * * `rent` - Rent
     * * `borrow` - Ausleihen
     * * `want_buy` - Want to Buy
     * * `want_rent` - Want to Rent
     */
    sales_type: SalesTypeEnum;
    price?: string | null;
};

/**
 * Serializer for Message model. Booking is referenced by UUID.
 */
export type MessageWritable = {
    booking: string;
    message: string;
    is_read?: boolean;
};

export type PaginatedBookListListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<BookListWritable>;
};

export type PaginatedBookingListListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<BookingListWritable>;
};

export type PaginatedCollectionEventListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<unknown>;
};

export type PaginatedCollectionItemListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<CollectionItemWritable>;
};

export type PaginatedCollectionListListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<CollectionListWritable>;
};

export type PaginatedGroupListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<GroupWritable>;
};

export type PaginatedImageListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<ImageWritable>;
};

export type PaginatedItemListListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<ItemListWritable>;
};

export type PaginatedMessageListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<MessageWritable>;
};

export type PaginatedProfileListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<ProfileWritable>;
};

export type PaginatedUserListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<UserWritable>;
};

/**
 * Full serializer for Book detail view.
 *
 * Read-side: exposes isbn, language, year, topic, metadata, authors,
 * genres, verlag (publisher name), shelf from Item.properties.
 *
 * Write-side: accepts authors (list of strings), genres (list of strings),
 * publisher (string), shelf (string), isbn, language, year, topic,
 * metadata.  The old UUID-based author_ids / genre_ids / verlag_id /
 * shelf_id fields are no longer accepted.
 */
export type PatchedBookWritable = {
    price?: string | null;
    isbn_write?: string;
    language_write?: string;
    year_write?: number | null;
    topic_write?: string;
    metadata_write?: unknown;
    authors_write?: Array<string>;
    genres_write?: Array<string>;
    publisher?: string;
    shelf_write?: string;
    /**
     * Category of the item
     *
     * * `books` - Bücher
     * * `clothing` - Kleidung
     * * `electronics` - Elektronik
     * * `furniture` - Möbel
     * * `garden` - Garten
     * * `kitchen` - Küche
     * * `other` - Andere
     * * `rooms` - Räume
     * * `sports` - Sport
     * * `tools` - Werkzeuge
     * * `toys` - Spielzeug
     * * `vehicles` - Fahrzeuge
     */
    category?: CategoryEnum | BlankEnum;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Interner Artikel, nicht für öffentliche Anzeige
     */
    internal?: boolean;
    /**
     * Kontaktinformationen öffentlich anzeigen
     */
    display_contact?: boolean;
    /**
     * How the item is offered: Sell, Donate, Rent, Borrow, Want to Buy, or Want to Rent.
     *
     * * `sell` - Sell
     * * `donate` - Donate
     * * `rent` - Rent
     * * `borrow` - Ausleihen
     * * `want_buy` - Want to Buy
     * * `want_rent` - Want to Rent
     */
    sales_type?: SalesTypeEnum;
    /**
     * Only used for formatting, price must always be per hour for rental items
     *
     * * `h` - Stündlich
     * * `d` - Täglich
     * * `w` - Wöchentlich
     */
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Selbstbedienungsvermietung ohne Zustimmung des Eigentümers erlauben
     */
    rental_self_service?: boolean;
    /**
     * Unbefristete Vermietungen ohne Rückgabedatum erlauben
     */
    rental_open_end?: boolean;
    /**
     * Zahlung über internes Zahlungssystem aktivieren
     */
    payment_enabled?: boolean;
    /**
     * Condition of the item
     *
     * * `0` - Neu
     * * `1` - Gebraucht
     * * `2` - Kaputt
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status873Enum;
    /**
     * Who can see this item: Public (everyone), Authenticated (logged-in users), Specific (selected users/groups), or Private (owner and co-owners only).
     *
     * * `0` - Öffentlich
     * * `1` - Authenticated
     * * `2` - Specific
     * * `3` - Private
     */
    visibility?: VisibilityEnum;
    /**
     * Category-specific properties stored as JSONB. For books: isbn, language, year, topic, metadata, authors, genres, publisher, shelf.
     */
    properties?: unknown;
};

/**
 * Detailed serializer for Booking where `item` is represented only by UUID.
 */
export type PatchedBookingWritable = {
    status?: Status164Enum;
    item?: string;
    /**
     * Von
     */
    time_from?: string | null;
    /**
     * Bis
     */
    time_to?: string | null;
    /**
     * Angebot
     *
     * Angebotener Preis für die Buchung
     */
    offer?: string | null;
    /**
     * Gegenangebot
     *
     * Gegenangebotspreis für die Buchung
     */
    counter_offer?: string | null;
    accepted_by?: string | null;
};

/**
 * Serializer for Collection model.
 */
export type PatchedCollectionWritable = {
    name?: string;
    description?: string;
};

/**
 * Serializer for CollectionItem model.
 */
export type PatchedCollectionItemWritable = {
    collection?: string;
    item_id?: string;
    /**
     * Optional note about this item
     */
    note?: string;
    ordering?: number;
};

/**
 * Serializer for Image model.
 */
export type PatchedImageWritable = {
    original?: string;
    ordering?: number | null;
    item?: string;
};

/**
 * Serializer for Item model.
 */
export type PatchedItemWritable = {
    price?: string | null;
    /**
     * Category of the item
     *
     * * `books` - Bücher
     * * `clothing` - Kleidung
     * * `electronics` - Elektronik
     * * `furniture` - Möbel
     * * `garden` - Garten
     * * `kitchen` - Küche
     * * `other` - Andere
     * * `rooms` - Räume
     * * `sports` - Sport
     * * `tools` - Werkzeuge
     * * `toys` - Spielzeug
     * * `vehicles` - Fahrzeuge
     */
    category?: CategoryEnum | BlankEnum;
    name?: string;
    slug?: string;
    description?: string;
    /**
     * Interner Artikel, nicht für öffentliche Anzeige
     */
    internal?: boolean;
    /**
     * Kontaktinformationen öffentlich anzeigen
     */
    display_contact?: boolean;
    /**
     * How the item is offered: Sell, Donate, Rent, Borrow, Want to Buy, or Want to Rent.
     *
     * * `sell` - Sell
     * * `donate` - Donate
     * * `rent` - Rent
     * * `borrow` - Ausleihen
     * * `want_buy` - Want to Buy
     * * `want_rent` - Want to Rent
     */
    sales_type?: SalesTypeEnum;
    /**
     * Only used for formatting, price must always be per hour for rental items
     *
     * * `h` - Stündlich
     * * `d` - Täglich
     * * `w` - Wöchentlich
     */
    rental_period?: RentalPeriodEnum | BlankEnum;
    /**
     * Selbstbedienungsvermietung ohne Zustimmung des Eigentümers erlauben
     */
    rental_self_service?: boolean;
    /**
     * Unbefristete Vermietungen ohne Rückgabedatum erlauben
     */
    rental_open_end?: boolean;
    /**
     * Zahlung über internes Zahlungssystem aktivieren
     */
    payment_enabled?: boolean;
    /**
     * Condition of the item
     *
     * * `0` - Neu
     * * `1` - Gebraucht
     * * `2` - Kaputt
     */
    condition?: ConditionEnum;
    active?: boolean;
    status?: Status873Enum;
    /**
     * Who can see this item: Public (everyone), Authenticated (logged-in users), Specific (selected users/groups), or Private (owner and co-owners only).
     *
     * * `0` - Öffentlich
     * * `1` - Authenticated
     * * `2` - Specific
     * * `3` - Private
     */
    visibility?: VisibilityEnum;
    /**
     * Category-specific properties stored as JSONB. For books: isbn, language, year, topic, metadata, authors, genres, publisher, shelf.
     */
    properties?: unknown;
};

/**
 * Serializer for Message model. Booking is referenced by UUID.
 */
export type PatchedMessageWritable = {
    booking?: string;
    message?: string;
    is_read?: boolean;
};

export type PatchedProfileWritable = {
    name?: string;
    phone?: string;
    bio?: string;
    address?: string;
    email_reminder?: boolean;
    profile_image?: string | null;
    /**
     * Preferred language
     *
     * UI language preference for this user.
     *
     * * `en` - Englisch
     * * `de` - Deutsch
     */
    language?: LanguageEnum | BlankEnum;
};

export type PatchedUserWritable = {
    /**
     * Benutzername
     *
     * Erforderlich. 150 Zeichen oder weniger. Nur Buchstaben, Ziffern und @/./+/-/_.
     */
    username?: string;
    /**
     * Name des Benutzers
     */
    name?: string;
    /**
     * E-Mail-Adresse
     */
    email?: string;
};

export type ProfileWritable = {
    name?: string;
    phone?: string;
    bio?: string;
    address?: string;
    email_reminder?: boolean;
    profile_image?: string | null;
    /**
     * Preferred language
     *
     * UI language preference for this user.
     *
     * * `en` - Englisch
     * * `de` - Deutsch
     */
    language?: LanguageEnum | BlankEnum;
};

export type UserWritable = {
    /**
     * Benutzername
     *
     * Erforderlich. 150 Zeichen oder weniger. Nur Buchstaben, Ziffern und @/./+/-/_.
     */
    username: string;
    /**
     * Name des Benutzers
     */
    name?: string;
    /**
     * E-Mail-Adresse
     */
    email?: string;
};

export type AuthTokenCreateData = {
    body: AuthToken;
    path?: never;
    query?: never;
    url: '/api/auth-token/';
};

export type AuthTokenCreateResponses = {
    200: AuthToken;
};

export type AuthTokenCreateResponse = AuthTokenCreateResponses[keyof AuthTokenCreateResponses];

export type BookingsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Feld, das zum Sortieren der Ergebnisse verwendet werden soll.
         */
        ordering?: string;
        /**
         * Eine Seitenzahl in der paginierten Ergebnismenge.
         */
        page?: number;
        /**
         * Ein Suchbegriff.
         */
        search?: string;
    };
    url: '/api/bookings/';
};

export type BookingsListResponses = {
    200: PaginatedBookingListList;
};

export type BookingsListResponse = BookingsListResponses[keyof BookingsListResponses];

export type BookingsCreateData = {
    body: BookingWritable;
    path?: never;
    query?: never;
    url: '/api/bookings/';
};

export type BookingsCreateResponses = {
    201: Booking;
};

export type BookingsCreateResponse = BookingsCreateResponses[keyof BookingsCreateResponses];

export type BookingsDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/bookings/{id}/';
};

export type BookingsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type BookingsDestroyResponse = BookingsDestroyResponses[keyof BookingsDestroyResponses];

export type BookingsRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/bookings/{id}/';
};

export type BookingsRetrieveResponses = {
    200: Booking;
};

export type BookingsRetrieveResponse = BookingsRetrieveResponses[keyof BookingsRetrieveResponses];

export type BookingsPartialUpdateData = {
    body?: PatchedBookingWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/bookings/{id}/';
};

export type BookingsPartialUpdateResponses = {
    200: Booking;
};

export type BookingsPartialUpdateResponse = BookingsPartialUpdateResponses[keyof BookingsPartialUpdateResponses];

export type BookingsUpdateData = {
    body: BookingWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/bookings/{id}/';
};

export type BookingsUpdateResponses = {
    200: Booking;
};

export type BookingsUpdateResponse = BookingsUpdateResponses[keyof BookingsUpdateResponses];

export type BooksListData = {
    body?: never;
    path?: never;
    query?: {
        author_name?: string;
        genre_name?: string;
        isbn?: string;
        language?: string;
        /**
         * Feld, das zum Sortieren der Ergebnisse verwendet werden soll.
         */
        ordering?: string;
        /**
         * Eine Seitenzahl in der paginierten Ergebnismenge.
         */
        page?: number;
        publisher_name?: string;
        /**
         * Ein Suchbegriff.
         */
        search?: string;
        shelf_name?: string;
        topic?: string;
        year?: number;
        year_max?: number;
        year_min?: number;
    };
    url: '/api/books/';
};

export type BooksListResponses = {
    200: PaginatedBookListList;
};

export type BooksListResponse = BooksListResponses[keyof BooksListResponses];

export type BooksCreateData = {
    body: BookWritable;
    path?: never;
    query?: never;
    url: '/api/books/';
};

export type BooksCreateResponses = {
    201: Book;
};

export type BooksCreateResponse = BooksCreateResponses[keyof BooksCreateResponses];

export type BooksDestroyData = {
    body?: never;
    path: {
        /**
         * Ein UUID-String, der item identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/books/{id}/';
};

export type BooksDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type BooksDestroyResponse = BooksDestroyResponses[keyof BooksDestroyResponses];

export type BooksRetrieveData = {
    body?: never;
    path: {
        /**
         * Ein UUID-String, der item identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/books/{id}/';
};

export type BooksRetrieveResponses = {
    200: Book;
};

export type BooksRetrieveResponse = BooksRetrieveResponses[keyof BooksRetrieveResponses];

export type BooksPartialUpdateData = {
    body?: PatchedBookWritable;
    path: {
        /**
         * Ein UUID-String, der item identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/books/{id}/';
};

export type BooksPartialUpdateResponses = {
    200: Book;
};

export type BooksPartialUpdateResponse = BooksPartialUpdateResponses[keyof BooksPartialUpdateResponses];

export type BooksUpdateData = {
    body: BookWritable;
    path: {
        /**
         * Ein UUID-String, der item identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/books/{id}/';
};

export type BooksUpdateResponses = {
    200: Book;
};

export type BooksUpdateResponse = BooksUpdateResponses[keyof BooksUpdateResponses];

export type BooksIsbnUpdateUpdateData = {
    body?: {
        /**
         * ISBN number to fetch book details from OpenLibrary API. If not provided, uses the book's existing ISBN.
         */
        isbn?: string;
    };
    path: {
        /**
         * Ein UUID-String, der item identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/books/{id}/isbn_update/';
};

export type BooksIsbnUpdateUpdateResponses = {
    200: Book;
};

export type BooksIsbnUpdateUpdateResponse = BooksIsbnUpdateUpdateResponses[keyof BooksIsbnUpdateUpdateResponses];

export type CollectionItemsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Eine Seitenzahl in der paginierten Ergebnismenge.
         */
        page?: number;
    };
    url: '/api/collection-items/';
};

export type CollectionItemsListResponses = {
    200: PaginatedCollectionItemList;
};

export type CollectionItemsListResponse = CollectionItemsListResponses[keyof CollectionItemsListResponses];

export type CollectionItemsCreateData = {
    body: CollectionItemWritable;
    path?: never;
    query?: never;
    url: '/api/collection-items/';
};

export type CollectionItemsCreateResponses = {
    201: CollectionItem;
};

export type CollectionItemsCreateResponse = CollectionItemsCreateResponses[keyof CollectionItemsCreateResponses];

export type CollectionItemsDestroyData = {
    body?: never;
    path: {
        /**
         * Ein UUID-String, der collection item identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/collection-items/{id}/';
};

export type CollectionItemsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type CollectionItemsDestroyResponse = CollectionItemsDestroyResponses[keyof CollectionItemsDestroyResponses];

export type CollectionItemsRetrieveData = {
    body?: never;
    path: {
        /**
         * Ein UUID-String, der collection item identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/collection-items/{id}/';
};

export type CollectionItemsRetrieveResponses = {
    200: CollectionItem;
};

export type CollectionItemsRetrieveResponse = CollectionItemsRetrieveResponses[keyof CollectionItemsRetrieveResponses];

export type CollectionItemsPartialUpdateData = {
    body?: PatchedCollectionItemWritable;
    path: {
        /**
         * Ein UUID-String, der collection item identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/collection-items/{id}/';
};

export type CollectionItemsPartialUpdateResponses = {
    200: CollectionItem;
};

export type CollectionItemsPartialUpdateResponse = CollectionItemsPartialUpdateResponses[keyof CollectionItemsPartialUpdateResponses];

export type CollectionItemsUpdateData = {
    body: CollectionItemWritable;
    path: {
        /**
         * Ein UUID-String, der collection item identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/collection-items/{id}/';
};

export type CollectionItemsUpdateResponses = {
    200: CollectionItem;
};

export type CollectionItemsUpdateResponse = CollectionItemsUpdateResponses[keyof CollectionItemsUpdateResponses];

export type CollectionsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Eine Seitenzahl in der paginierten Ergebnismenge.
         */
        page?: number;
    };
    url: '/api/collections/';
};

export type CollectionsListResponses = {
    200: PaginatedCollectionListList;
};

export type CollectionsListResponse = CollectionsListResponses[keyof CollectionsListResponses];

export type CollectionsCreateData = {
    body: CollectionWritable;
    path?: never;
    query?: never;
    url: '/api/collections/';
};

export type CollectionsCreateResponses = {
    201: Collection;
};

export type CollectionsCreateResponse = CollectionsCreateResponses[keyof CollectionsCreateResponses];

export type CollectionsDestroyData = {
    body?: never;
    path: {
        /**
         * Ein UUID-String, der collection identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/collections/{id}/';
};

export type CollectionsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type CollectionsDestroyResponse = CollectionsDestroyResponses[keyof CollectionsDestroyResponses];

export type CollectionsRetrieveData = {
    body?: never;
    path: {
        /**
         * Ein UUID-String, der collection identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/collections/{id}/';
};

export type CollectionsRetrieveResponses = {
    200: Collection;
};

export type CollectionsRetrieveResponse = CollectionsRetrieveResponses[keyof CollectionsRetrieveResponses];

export type CollectionsPartialUpdateData = {
    body?: PatchedCollectionWritable;
    path: {
        /**
         * Ein UUID-String, der collection identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/collections/{id}/';
};

export type CollectionsPartialUpdateResponses = {
    200: Collection;
};

export type CollectionsPartialUpdateResponse = CollectionsPartialUpdateResponses[keyof CollectionsPartialUpdateResponses];

export type CollectionsUpdateData = {
    body: CollectionWritable;
    path: {
        /**
         * Ein UUID-String, der collection identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/collections/{id}/';
};

export type CollectionsUpdateResponses = {
    200: Collection;
};

export type CollectionsUpdateResponse = CollectionsUpdateResponses[keyof CollectionsUpdateResponses];

export type CollectionsAddItemCreateData = {
    body: CollectionWritable;
    path: {
        /**
         * Ein UUID-String, der collection identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/collections/{id}/add-item/';
};

export type CollectionsAddItemCreateResponses = {
    200: Collection;
};

export type CollectionsAddItemCreateResponse = CollectionsAddItemCreateResponses[keyof CollectionsAddItemCreateResponses];

export type CollectionsBulkAddItemsCreateData = {
    body: CollectionWritable;
    path: {
        /**
         * Ein UUID-String, der collection identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/collections/{id}/bulk-add-items/';
};

export type CollectionsBulkAddItemsCreateResponses = {
    200: Collection;
};

export type CollectionsBulkAddItemsCreateResponse = CollectionsBulkAddItemsCreateResponses[keyof CollectionsBulkAddItemsCreateResponses];

export type CollectionsBulkRemoveItemsCreateData = {
    body: CollectionWritable;
    path: {
        /**
         * Ein UUID-String, der collection identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/collections/{id}/bulk-remove-items/';
};

export type CollectionsBulkRemoveItemsCreateResponses = {
    200: Collection;
};

export type CollectionsBulkRemoveItemsCreateResponse = CollectionsBulkRemoveItemsCreateResponses[keyof CollectionsBulkRemoveItemsCreateResponses];

export type CollectionsHistoryListData = {
    body?: never;
    path: {
        /**
         * Ein UUID-String, der collection identifiziert.
         */
        id: string;
    };
    query?: {
        /**
         * Eine Seitenzahl in der paginierten Ergebnismenge.
         */
        page?: number;
    };
    url: '/api/collections/{id}/history/';
};

export type CollectionsHistoryListResponses = {
    200: PaginatedCollectionEventList;
};

export type CollectionsHistoryListResponse = CollectionsHistoryListResponses[keyof CollectionsHistoryListResponses];

export type CollectionsManagePermissionsCreateData = {
    body: CollectionWritable;
    path: {
        /**
         * Ein UUID-String, der collection identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/collections/{id}/manage_permissions/';
};

export type CollectionsManagePermissionsCreateResponses = {
    200: Collection;
};

export type CollectionsManagePermissionsCreateResponse = CollectionsManagePermissionsCreateResponses[keyof CollectionsManagePermissionsCreateResponses];

export type CollectionsPermissionsListData = {
    body?: never;
    path: {
        /**
         * Ein UUID-String, der collection identifiziert.
         */
        id: string;
    };
    query?: {
        /**
         * Eine Seitenzahl in der paginierten Ergebnismenge.
         */
        page?: number;
    };
    url: '/api/collections/{id}/permissions/';
};

export type CollectionsPermissionsListResponses = {
    200: PaginatedCollectionGrantList;
};

export type CollectionsPermissionsListResponse = CollectionsPermissionsListResponses[keyof CollectionsPermissionsListResponses];

export type CollectionsRemoveItemCreateData = {
    body: CollectionWritable;
    path: {
        /**
         * Ein UUID-String, der collection identifiziert.
         */
        id: string;
        item_id: string;
    };
    query?: never;
    url: '/api/collections/{id}/remove-item/{item_id}/';
};

export type CollectionsRemoveItemCreateResponses = {
    200: Collection;
};

export type CollectionsRemoveItemCreateResponse = CollectionsRemoveItemCreateResponses[keyof CollectionsRemoveItemCreateResponses];

export type CollectionsForItemListData = {
    body?: never;
    path: {
        item_id: string;
    };
    query?: {
        /**
         * Eine Seitenzahl in der paginierten Ergebnismenge.
         */
        page?: number;
    };
    url: '/api/collections/for-item/{item_id}/';
};

export type CollectionsForItemListResponses = {
    200: PaginatedCollectionListList;
};

export type CollectionsForItemListResponse = CollectionsForItemListResponses[keyof CollectionsForItemListResponses];

export type CollectionsMyCollectionsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Eine Seitenzahl in der paginierten Ergebnismenge.
         */
        page?: number;
    };
    url: '/api/collections/my-collections/';
};

export type CollectionsMyCollectionsListResponses = {
    200: PaginatedCollectionListList;
};

export type CollectionsMyCollectionsListResponse = CollectionsMyCollectionsListResponses[keyof CollectionsMyCollectionsListResponses];

export type ConfigRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/config/';
};

export type ConfigRetrieveResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type GroupsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Eine Seitenzahl in der paginierten Ergebnismenge.
         */
        page?: number;
    };
    url: '/api/groups/';
};

export type GroupsListResponses = {
    200: PaginatedGroupList;
};

export type GroupsListResponse = GroupsListResponses[keyof GroupsListResponses];

export type GroupsRetrieveData = {
    body?: never;
    path: {
        /**
         * Ein eindeutiger Ganzzahl-Wert, der Gruppe identifiziert.
         */
        id: number;
    };
    query?: never;
    url: '/api/groups/{id}/';
};

export type GroupsRetrieveResponses = {
    200: Group;
};

export type GroupsRetrieveResponse = GroupsRetrieveResponses[keyof GroupsRetrieveResponses];

export type ImagesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Eine Seitenzahl in der paginierten Ergebnismenge.
         */
        page?: number;
    };
    url: '/api/images/';
};

export type ImagesListResponses = {
    200: PaginatedImageList;
};

export type ImagesListResponse = ImagesListResponses[keyof ImagesListResponses];

export type ImagesCreateData = {
    body: ImageWritable;
    path?: never;
    query?: never;
    url: '/api/images/';
};

export type ImagesCreateResponses = {
    201: Image;
};

export type ImagesCreateResponse = ImagesCreateResponses[keyof ImagesCreateResponses];

export type ImagesDestroyData = {
    body?: never;
    path: {
        /**
         * Ein UUID-String, der image identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/images/{id}/';
};

export type ImagesDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ImagesDestroyResponse = ImagesDestroyResponses[keyof ImagesDestroyResponses];

export type ImagesRetrieveData = {
    body?: never;
    path: {
        /**
         * Ein UUID-String, der image identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/images/{id}/';
};

export type ImagesRetrieveResponses = {
    200: Image;
};

export type ImagesRetrieveResponse = ImagesRetrieveResponses[keyof ImagesRetrieveResponses];

export type ImagesPartialUpdateData = {
    body?: PatchedImageWritable;
    path: {
        /**
         * Ein UUID-String, der image identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/images/{id}/';
};

export type ImagesPartialUpdateResponses = {
    200: Image;
};

export type ImagesPartialUpdateResponse = ImagesPartialUpdateResponses[keyof ImagesPartialUpdateResponses];

export type ImagesUpdateData = {
    body: ImageWritable;
    path: {
        /**
         * Ein UUID-String, der image identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/images/{id}/';
};

export type ImagesUpdateResponses = {
    200: Image;
};

export type ImagesUpdateResponse = ImagesUpdateResponses[keyof ImagesUpdateResponses];

export type ItemsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Category of the item
         *
         * * `books` - Bücher
         * * `clothing` - Kleidung
         * * `electronics` - Elektronik
         * * `furniture` - Möbel
         * * `garden` - Garten
         * * `kitchen` - Küche
         * * `other` - Andere
         * * `rooms` - Räume
         * * `sports` - Sport
         * * `tools` - Werkzeuge
         * * `toys` - Spielzeug
         * * `vehicles` - Fahrzeuge
         */
        category?: 'books' | 'clothing' | 'electronics' | 'furniture' | 'garden' | 'kitchen' | 'other' | 'rooms' | 'sports' | 'tools' | 'toys' | 'vehicles';
        /**
         * Condition of the item
         *
         * * `0` - Neu
         * * `1` - Gebraucht
         * * `2` - Kaputt
         */
        conditions?: Array<0 | 1 | 2>;
        created_after?: string;
        created_before?: string;
        max_price?: number;
        min_price?: number;
        /**
         * Feld, das zum Sortieren der Ergebnisse verwendet werden soll.
         */
        ordering?: string;
        /**
         * Eine Seitenzahl in der paginierten Ergebnismenge.
         */
        page?: number;
        published?: boolean;
        /**
         * How the item is offered: Sell, Donate, Rent, Borrow, Want to Buy, or Want to Rent.
         *
         * * `sell` - Sell
         * * `donate` - Donate
         * * `rent` - Rent
         * * `borrow` - Ausleihen
         * * `want_buy` - Want to Buy
         * * `want_rent` - Want to Rent
         */
        sales_type?: Array<'borrow' | 'donate' | 'rent' | 'sell' | 'want_buy' | 'want_rent'>;
        /**
         * Ein Suchbegriff.
         */
        search?: string;
        /**
         * * `0` - Entwurf
         * * `2` - Verfügbar
         * * `3` - Reserviert
         * * `4` - Rented
         * * `5` - Verkauft
         */
        status?: Array<0 | 2 | 3 | 4 | 5>;
        user?: string;
    };
    url: '/api/items/';
};

export type ItemsListResponses = {
    200: PaginatedItemListList;
};

export type ItemsListResponse = ItemsListResponses[keyof ItemsListResponses];

export type ItemsCreateData = {
    body: ItemWritable;
    path?: never;
    query?: never;
    url: '/api/items/';
};

export type ItemsCreateResponses = {
    201: Item;
};

export type ItemsCreateResponse = ItemsCreateResponses[keyof ItemsCreateResponses];

export type ItemsDestroyData = {
    body?: never;
    path: {
        /**
         * Ein UUID-String, der item identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/items/{id}/';
};

export type ItemsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ItemsDestroyResponse = ItemsDestroyResponses[keyof ItemsDestroyResponses];

export type ItemsRetrieveData = {
    body?: never;
    path: {
        /**
         * Ein UUID-String, der item identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/items/{id}/';
};

export type ItemsRetrieveResponses = {
    200: Item;
};

export type ItemsRetrieveResponse = ItemsRetrieveResponses[keyof ItemsRetrieveResponses];

export type ItemsPartialUpdateData = {
    body?: PatchedItemWritable;
    path: {
        /**
         * Ein UUID-String, der item identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/items/{id}/';
};

export type ItemsPartialUpdateResponses = {
    200: Item;
};

export type ItemsPartialUpdateResponse = ItemsPartialUpdateResponses[keyof ItemsPartialUpdateResponses];

export type ItemsUpdateData = {
    body: ItemWritable;
    path: {
        /**
         * Ein UUID-String, der item identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/items/{id}/';
};

export type ItemsUpdateResponses = {
    200: Item;
};

export type ItemsUpdateResponse = ItemsUpdateResponses[keyof ItemsUpdateResponses];

export type ItemsAiDescribeUpdateData = {
    body: ItemWritable;
    path: {
        /**
         * Ein UUID-String, der item identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/items/{id}/ai_describe/';
};

export type ItemsAiDescribeUpdateResponses = {
    200: Item;
};

export type ItemsAiDescribeUpdateResponse = ItemsAiDescribeUpdateResponses[keyof ItemsAiDescribeUpdateResponses];

export type ItemsAiImageUpdateData = {
    body: ItemWritable;
    path: {
        /**
         * Ein UUID-String, der item identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/items/{id}/ai_image/';
};

export type ItemsAiImageUpdateResponses = {
    200: Item;
};

export type ItemsAiImageUpdateResponse = ItemsAiImageUpdateResponses[keyof ItemsAiImageUpdateResponses];

export type ItemsCoOwnersDestroyData = {
    body?: never;
    path: {
        /**
         * Ein UUID-String, der item identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/items/{id}/co-owners/';
};

export type ItemsCoOwnersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ItemsCoOwnersDestroyResponse = ItemsCoOwnersDestroyResponses[keyof ItemsCoOwnersDestroyResponses];

export type ItemsCoOwnersRetrieveData = {
    body?: never;
    path: {
        /**
         * Ein UUID-String, der item identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/items/{id}/co-owners/';
};

export type ItemsCoOwnersRetrieveResponses = {
    200: Item;
};

export type ItemsCoOwnersRetrieveResponse = ItemsCoOwnersRetrieveResponses[keyof ItemsCoOwnersRetrieveResponses];

export type ItemsCoOwnersCreateData = {
    body: ItemWritable;
    path: {
        /**
         * Ein UUID-String, der item identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/items/{id}/co-owners/';
};

export type ItemsCoOwnersCreateResponses = {
    200: Item;
};

export type ItemsCoOwnersCreateResponse = ItemsCoOwnersCreateResponses[keyof ItemsCoOwnersCreateResponses];

export type ItemsReorderImagesUpdateData = {
    body: ItemWritable;
    path: {
        /**
         * Ein UUID-String, der item identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/items/{id}/reorder_images/';
};

export type ItemsReorderImagesUpdateResponses = {
    200: Item;
};

export type ItemsReorderImagesUpdateResponse = ItemsReorderImagesUpdateResponses[keyof ItemsReorderImagesUpdateResponses];

export type ItemsViewersDestroyData = {
    body?: never;
    path: {
        /**
         * Ein UUID-String, der item identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/items/{id}/viewers/';
};

export type ItemsViewersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ItemsViewersDestroyResponse = ItemsViewersDestroyResponses[keyof ItemsViewersDestroyResponses];

export type ItemsViewersRetrieveData = {
    body?: never;
    path: {
        /**
         * Ein UUID-String, der item identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/items/{id}/viewers/';
};

export type ItemsViewersRetrieveResponses = {
    200: Item;
};

export type ItemsViewersRetrieveResponse = ItemsViewersRetrieveResponses[keyof ItemsViewersRetrieveResponses];

export type ItemsViewersCreateData = {
    body: ItemWritable;
    path: {
        /**
         * Ein UUID-String, der item identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/items/{id}/viewers/';
};

export type ItemsViewersCreateResponses = {
    200: Item;
};

export type ItemsViewersCreateResponse = ItemsViewersCreateResponses[keyof ItemsViewersCreateResponses];

export type MessagesListData = {
    body?: never;
    path?: never;
    query?: {
        booking?: string;
        created_at_after?: string;
        created_at_before?: string;
        is_read?: boolean;
        /**
         * Feld, das zum Sortieren der Ergebnisse verwendet werden soll.
         */
        ordering?: string;
        /**
         * Eine Seitenzahl in der paginierten Ergebnismenge.
         */
        page?: number;
        sender?: string;
        /**
         * Unread messages received by current user
         */
        unread_received?: boolean;
    };
    url: '/api/messages/';
};

export type MessagesListResponses = {
    200: PaginatedMessageList;
};

export type MessagesListResponse = MessagesListResponses[keyof MessagesListResponses];

export type MessagesCreateData = {
    body: MessageWritable;
    path?: never;
    query?: never;
    url: '/api/messages/';
};

export type MessagesCreateResponses = {
    201: Message;
};

export type MessagesCreateResponse = MessagesCreateResponses[keyof MessagesCreateResponses];

export type MessagesDestroyData = {
    body?: never;
    path: {
        /**
         * Ein UUID-String, der message identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/messages/{id}/';
};

export type MessagesDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type MessagesDestroyResponse = MessagesDestroyResponses[keyof MessagesDestroyResponses];

export type MessagesRetrieveData = {
    body?: never;
    path: {
        /**
         * Ein UUID-String, der message identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/messages/{id}/';
};

export type MessagesRetrieveResponses = {
    200: Message;
};

export type MessagesRetrieveResponse = MessagesRetrieveResponses[keyof MessagesRetrieveResponses];

export type MessagesPartialUpdateData = {
    body?: PatchedMessageWritable;
    path: {
        /**
         * Ein UUID-String, der message identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/messages/{id}/';
};

export type MessagesPartialUpdateResponses = {
    200: Message;
};

export type MessagesPartialUpdateResponse = MessagesPartialUpdateResponses[keyof MessagesPartialUpdateResponses];

export type MessagesUpdateData = {
    body: MessageWritable;
    path: {
        /**
         * Ein UUID-String, der message identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/messages/{id}/';
};

export type MessagesUpdateResponses = {
    200: Message;
};

export type MessagesUpdateResponse = MessagesUpdateResponses[keyof MessagesUpdateResponses];

export type NotificationPreferencesMeRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/notification-preferences/me/';
};

export type NotificationPreferencesMeRetrieveResponses = {
    200: NotificationPreferenceMe;
};

export type NotificationPreferencesMeRetrieveResponse = NotificationPreferencesMeRetrieveResponses[keyof NotificationPreferencesMeRetrieveResponses];

export type NotificationPreferencesMePartialUpdateData = {
    body?: PatchedNotificationPreferenceMe;
    path?: never;
    query?: never;
    url: '/api/notification-preferences/me/';
};

export type NotificationPreferencesMePartialUpdateResponses = {
    200: NotificationPreferenceMe;
};

export type NotificationPreferencesMePartialUpdateResponse = NotificationPreferencesMePartialUpdateResponses[keyof NotificationPreferencesMePartialUpdateResponses];

export type ProfilesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Eine Seitenzahl in der paginierten Ergebnismenge.
         */
        page?: number;
    };
    url: '/api/profiles/';
};

export type ProfilesListResponses = {
    200: PaginatedProfileList;
};

export type ProfilesListResponse = ProfilesListResponses[keyof ProfilesListResponses];

export type ProfilesRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/profiles/{id}/';
};

export type ProfilesRetrieveResponses = {
    200: Profile;
};

export type ProfilesRetrieveResponse = ProfilesRetrieveResponses[keyof ProfilesRetrieveResponses];

export type ProfilesMeRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/profiles/me/';
};

export type ProfilesMeRetrieveResponses = {
    200: Profile;
};

export type ProfilesMeRetrieveResponse = ProfilesMeRetrieveResponses[keyof ProfilesMeRetrieveResponses];

export type ProfilesMePartialUpdateData = {
    body?: PatchedProfileWritable;
    path?: never;
    query?: never;
    url: '/api/profiles/me/';
};

export type ProfilesMePartialUpdateResponses = {
    200: Profile;
};

export type ProfilesMePartialUpdateResponse = ProfilesMePartialUpdateResponses[keyof ProfilesMePartialUpdateResponses];

export type PublicBookingsListData = {
    body?: never;
    path?: never;
    query?: {
        created_at_after?: string;
        created_at_before?: string;
        item?: string;
        /**
         * Feld, das zum Sortieren der Ergebnisse verwendet werden soll.
         */
        ordering?: string;
        /**
         * Eine Seitenzahl in der paginierten Ergebnismenge.
         */
        page?: number;
        /**
         * Role filter (owner/renter)
         */
        role?: string;
        /**
         * Ein Suchbegriff.
         */
        search?: string;
        /**
         * * `1` - Ausstehend
         * * `2` - Abgebrochen
         * * `3` - Bestätigt
         * * `4` - Abgeschlossen
         * * `5` - Abgelehnt
         */
        status?: Array<1 | 2 | 3 | 4 | 5>;
        time_from_after?: string;
        time_from_before?: string;
        time_to_after?: string;
        time_to_before?: string;
        time_to_isnull?: boolean;
        user?: string;
    };
    url: '/api/public-bookings/';
};

export type PublicBookingsListResponses = {
    200: PaginatedBookingListList;
};

export type PublicBookingsListResponse = PublicBookingsListResponses[keyof PublicBookingsListResponses];

export type PublicBookingsRetrieveData = {
    body?: never;
    path: {
        /**
         * Ein UUID-String, der booking identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/public-bookings/{id}/';
};

export type PublicBookingsRetrieveResponses = {
    200: Booking;
};

export type PublicBookingsRetrieveResponse = PublicBookingsRetrieveResponses[keyof PublicBookingsRetrieveResponses];

export type PublicItemsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Category of the item
         *
         * * `books` - Bücher
         * * `clothing` - Kleidung
         * * `electronics` - Elektronik
         * * `furniture` - Möbel
         * * `garden` - Garten
         * * `kitchen` - Küche
         * * `other` - Andere
         * * `rooms` - Räume
         * * `sports` - Sport
         * * `tools` - Werkzeuge
         * * `toys` - Spielzeug
         * * `vehicles` - Fahrzeuge
         */
        category?: 'books' | 'clothing' | 'electronics' | 'furniture' | 'garden' | 'kitchen' | 'other' | 'rooms' | 'sports' | 'tools' | 'toys' | 'vehicles';
        /**
         * Condition of the item
         *
         * * `0` - Neu
         * * `1` - Gebraucht
         * * `2` - Kaputt
         */
        conditions?: Array<0 | 1 | 2>;
        created_after?: string;
        created_before?: string;
        max_price?: number;
        min_price?: number;
        /**
         * Feld, das zum Sortieren der Ergebnisse verwendet werden soll.
         */
        ordering?: string;
        /**
         * Eine Seitenzahl in der paginierten Ergebnismenge.
         */
        page?: number;
        published?: boolean;
        /**
         * How the item is offered: Sell, Donate, Rent, Borrow, Want to Buy, or Want to Rent.
         *
         * * `sell` - Sell
         * * `donate` - Donate
         * * `rent` - Rent
         * * `borrow` - Ausleihen
         * * `want_buy` - Want to Buy
         * * `want_rent` - Want to Rent
         */
        sales_type?: Array<'borrow' | 'donate' | 'rent' | 'sell' | 'want_buy' | 'want_rent'>;
        /**
         * Ein Suchbegriff.
         */
        search?: string;
        /**
         * * `0` - Entwurf
         * * `2` - Verfügbar
         * * `3` - Reserviert
         * * `4` - Rented
         * * `5` - Verkauft
         */
        status?: Array<0 | 2 | 3 | 4 | 5>;
        user?: string;
    };
    url: '/api/public-items/';
};

export type PublicItemsListResponses = {
    200: PaginatedItemListList;
};

export type PublicItemsListResponse = PublicItemsListResponses[keyof PublicItemsListResponses];

export type PublicItemsRetrieveData = {
    body?: never;
    path: {
        /**
         * Ein UUID-String, der item identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/public-items/{id}/';
};

export type PublicItemsRetrieveResponses = {
    200: Item;
};

export type PublicItemsRetrieveResponse = PublicItemsRetrieveResponses[keyof PublicItemsRetrieveResponses];

export type SchemaRetrieveData = {
    body?: never;
    path?: never;
    query?: {
        format?: 'json' | 'yaml';
        lang?: 'de' | 'en';
    };
    url: '/api/schema/';
};

export type SchemaRetrieveResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type SchemaRetrieveResponse = SchemaRetrieveResponses[keyof SchemaRetrieveResponses];

export type UsersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Eine Seitenzahl in der paginierten Ergebnismenge.
         */
        page?: number;
    };
    url: '/api/users/';
};

export type UsersListResponses = {
    200: PaginatedUserList;
};

export type UsersListResponse = UsersListResponses[keyof UsersListResponses];

export type UsersRetrieveData = {
    body?: never;
    path: {
        /**
         * Ein UUID-String, der Benutzer identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersRetrieveResponses = {
    200: User;
};

export type UsersRetrieveResponse = UsersRetrieveResponses[keyof UsersRetrieveResponses];

export type UsersPartialUpdateData = {
    body?: PatchedUserWritable;
    path: {
        /**
         * Ein UUID-String, der Benutzer identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersPartialUpdateResponses = {
    200: User;
};

export type UsersPartialUpdateResponse = UsersPartialUpdateResponses[keyof UsersPartialUpdateResponses];

export type UsersUpdateData = {
    body: UserWritable;
    path: {
        /**
         * Ein UUID-String, der Benutzer identifiziert.
         */
        id: string;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersUpdateResponses = {
    200: User;
};

export type UsersUpdateResponse = UsersUpdateResponses[keyof UsersUpdateResponses];

export type UsersMeRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me/';
};

export type UsersMeRetrieveResponses = {
    200: User;
};

export type UsersMeRetrieveResponse = UsersMeRetrieveResponses[keyof UsersMeRetrieveResponses];
