# Generated by Django 6.0.3 on 2026-03-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('de', 'German')], default='', help_text='UI language preference for this user.', max_length=10, verbose_name='preferred language'),
        ),
    ]
