# Generated by Django 6.0.4 on 2026-04-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_profile_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="federation_discoverable",
            field=models.BooleanField(
                default=True,
                help_text="Include this profile in WebFinger discovery and the Mastodon-compatible actor endpoint. Requires federation_enabled on the User as well.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="federation_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Allow this user's profile and items to be federated via ActivityPub. Disabling this removes the user from WebFinger lookup and stops publishing their items to peer instances.",
            ),
        ),
    ]
