# Generated by Django 6.0.6 on 2026-06-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_federation_discoverable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="matrix_id",
            field=models.CharField(
                blank=True,
                help_text="Matrix user ID for notifications, e.g. @alice:matrix.org",
                max_length=255,
                verbose_name="Matrix ID",
            ),
        ),
    ]
