# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_profile_matrix_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="pwa_install_dismissed",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "User has dismissed the home-screen prompt to install Bubble as a "
                    "PWA. Once set, the prompt is not shown again."
                ),
            ),
        ),
    ]
