apiVersion: v2
name: sharebubble
description: A Helm chart for Sharebubble
type: application
version: 0.5.1
appVersion: '0.1.2'

keywords:
  - bubble
  - sharebubble
  - community
  - django
  - nginx

maintainers:
  - name: Sharebubble community
    url: https://github.com/sharebubble

home: https://github.com/sharebubble/bubble
sources:
  - https://github.com/sharebubble/bubble

dependencies:
  - name: rustfs
    version: "0.8.0"
    repository: "https://charts.rustfs.com"
    condition: rustfs.enabled
