# Generated by Django 6.0.6 on 2026-08-14 18:52

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0006_add_performance_indexes"),
        ("items", "0018_add_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoinValuation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total value of the transaction in community coins.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Value per rental period in community coins. Set for rentals only; ``amount`` holds the resulting total for the booked duration.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Rate",
                    ),
                ),
                (
                    "rental_period",
                    models.CharField(
                        blank=True,
                        choices=[("h", "Hourly"), ("d", "Daily"), ("w", "Weekly")],
                        help_text="Period the rate applies to, as it stood at valuation time.",
                        max_length=1,
                        verbose_name="Rental period",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        help_text="The settled transaction this valuation belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coin_valuation",
                        to="bookings.booking",
                        verbose_name="Booking",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coin_valuations",
                        to="items.item",
                        verbose_name="Item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The person who received the item and set this value.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coin_valuations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coin valuation",
                "verbose_name_plural": "Coin valuations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["item", "-created_at"], name="coins_item_created_idx"
                    ),
                    models.Index(fields=["user", "item"], name="coins_user_item_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0)),
                        name="coin_valuation_amount_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("rate__isnull", True), ("rate__gte", 0), _connector="OR"
                        ),
                        name="coin_valuation_rate_not_negative",
                    ),
                ],
            },
        ),
    ]
