# Generated by Django 6.0.4 on 2026-04-30 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("items", "0013_historicalitem_ap_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstanceActorKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_key_pem", models.TextField(verbose_name="Public key (PEM)")),
                (
                    "private_key_encrypted",
                    models.TextField(verbose_name="Private key (encrypted)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Instance actor key",
                "verbose_name_plural": "Instance actor keys",
            },
        ),
        migrations.CreateModel(
            name="RemoteInstance",
            fields=[
                (
                    "domain",
                    models.CharField(
                        help_text="Bare domain name, e.g. 'other.bubble.example'",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Domain",
                    ),
                ),
                (
                    "software",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Software"
                    ),
                ),
                (
                    "software_version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Software version"
                    ),
                ),
                (
                    "nodeinfo_url",
                    models.URLField(blank=True, verbose_name="NodeInfo URL"),
                ),
                (
                    "allowlist_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("allowed", "Allowed"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Allowlist state",
                    ),
                ),
                (
                    "inbox_url",
                    models.URLField(
                        blank=True,
                        help_text="Populated when the instance actor is fetched.",
                        verbose_name="Shared inbox URL",
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(auto_now_add=True, verbose_name="First seen"),
                ),
                (
                    "last_seen",
                    models.DateTimeField(auto_now=True, verbose_name="Last seen"),
                ),
            ],
            options={
                "verbose_name": "Remote instance",
                "verbose_name_plural": "Remote instances",
                "ordering": ["domain"],
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "follower_ap_id",
                    models.URLField(max_length=2048, verbose_name="Follower actor ID"),
                ),
                (
                    "followee_ap_id",
                    models.URLField(max_length=2048, verbose_name="Followee actor ID"),
                ),
                (
                    "accepted",
                    models.BooleanField(default=False, verbose_name="Accepted"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Follow",
                "verbose_name_plural": "Follows",
                "unique_together": {("follower_ap_id", "followee_ap_id")},
            },
        ),
        migrations.CreateModel(
            name="InboundActivity",
            fields=[
                (
                    "ap_id",
                    models.CharField(
                        max_length=2048,
                        primary_key=True,
                        serialize=False,
                        verbose_name="AP activity ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(max_length=50, verbose_name="Activity type"),
                ),
                (
                    "actor_uri",
                    models.URLField(max_length=2048, verbose_name="Actor URI"),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Processed at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("raw_jsonld", models.JSONField(verbose_name="Raw JSON-LD")),
                ("error", models.TextField(blank=True, verbose_name="Error")),
            ],
            options={
                "verbose_name": "Inbound activity",
                "verbose_name_plural": "Inbound activities",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["actor_uri"], name="federation__actor_u_0e3644_idx"
                    ),
                    models.Index(
                        fields=["status"], name="federation__status_7965cd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LocalActorKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_key_pem", models.TextField(verbose_name="Public key (PEM)")),
                (
                    "private_key_encrypted",
                    models.TextField(
                        help_text="Fernet-encrypted RSA private key, base64-encoded.",
                        verbose_name="Private key (encrypted)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actor_key",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Local actor key",
                "verbose_name_plural": "Local actor keys",
            },
        ),
        migrations.CreateModel(
            name="OutboundDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_id",
                    models.CharField(max_length=2048, verbose_name="Activity ID (URI)"),
                ),
                (
                    "activity_type",
                    models.CharField(max_length=50, verbose_name="Activity type"),
                ),
                ("payload", models.JSONField(verbose_name="Payload")),
                (
                    "recipient_inbox",
                    models.URLField(
                        max_length=2048, verbose_name="Recipient inbox URL"
                    ),
                ),
                (
                    "signing_actor_uri",
                    models.URLField(max_length=2048, verbose_name="Signing actor URI"),
                ),
                (
                    "attempt",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Attempt count"
                    ),
                ),
                (
                    "next_attempt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Next attempt at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("dead", "Dead (max retries exceeded)"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("last_error", models.TextField(blank=True, verbose_name="Last error")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Outbound delivery",
                "verbose_name_plural": "Outbound deliveries",
                "ordering": ["next_attempt_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at"],
                        name="federation__status_1262fd_idx",
                    ),
                    models.Index(
                        fields=["activity_id"], name="federation__activit_358e9e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RemoteActor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ap_id",
                    models.URLField(
                        max_length=2048, unique=True, verbose_name="AP actor ID"
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        default="Person",
                        help_text="AP type: Person, Application, Service, etc.",
                        max_length=50,
                        verbose_name="Actor type",
                    ),
                ),
                (
                    "preferred_username",
                    models.CharField(max_length=255, verbose_name="Preferred username"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Display name"
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="Summary / bio")),
                (
                    "inbox_url",
                    models.URLField(max_length=2048, verbose_name="Inbox URL"),
                ),
                (
                    "shared_inbox_url",
                    models.URLField(
                        blank=True, max_length=2048, verbose_name="Shared inbox URL"
                    ),
                ),
                (
                    "outbox_url",
                    models.URLField(
                        blank=True, max_length=2048, verbose_name="Outbox URL"
                    ),
                ),
                ("public_key_pem", models.TextField(verbose_name="Public key (PEM)")),
                (
                    "icon_url",
                    models.URLField(
                        blank=True, max_length=2048, verbose_name="Avatar URL"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, max_length=2048, verbose_name="Profile HTML URL"
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last fetched at"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actors",
                        to="federation.remoteinstance",
                        verbose_name="Instance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote actor",
                "verbose_name_plural": "Remote actors",
                "ordering": ["instance__domain", "preferred_username"],
            },
        ),
        migrations.CreateModel(
            name="RemoteItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ap_id",
                    models.URLField(
                        max_length=2048, unique=True, verbose_name="AP item ID"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Category"
                    ),
                ),
                (
                    "sales_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Sales type"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Price",
                    ),
                ),
                (
                    "price_currency",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Currency"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Condition"
                    ),
                ),
                (
                    "status",
                    models.CharField(blank=True, max_length=50, verbose_name="Status"),
                ),
                (
                    "properties",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Properties"
                    ),
                ),
                ("raw_jsonld", models.JSONField(verbose_name="Raw JSON-LD")),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="federation.remoteinstance",
                        verbose_name="Instance",
                    ),
                ),
                (
                    "remote_actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="federation.remoteactor",
                        verbose_name="Remote actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote item",
                "verbose_name_plural": "Remote items",
                "ordering": ["-last_updated_at"],
            },
        ),
        migrations.CreateModel(
            name="RemoteItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Ordering"
                    ),
                ),
                ("url", models.URLField(max_length=2048, verbose_name="Image URL")),
                (
                    "alt",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Alt text"
                    ),
                ),
                (
                    "remote_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="federation.remoteitem",
                        verbose_name="Remote item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote item image",
                "verbose_name_plural": "Remote item images",
                "ordering": ["ordering"],
            },
        ),
        migrations.CreateModel(
            name="RemoteFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remote_favorites",
                        to="items.item",
                        verbose_name="Item",
                    ),
                ),
                (
                    "remote_actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="federation.remoteactor",
                        verbose_name="Remote actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote favorite",
                "verbose_name_plural": "Remote favorites",
                "unique_together": {("remote_actor", "item")},
            },
        ),
    ]
