# Generated by Django 6.0.4 on 2026-04-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteinstance',
            name='catalog_url',
            field=models.URLField(blank=True, help_text='Paginated ActivityPub outbox or collection URL used for backfill. Auto-populated from the instance actor when left empty.', verbose_name='Catalog / outbox URL'),
        ),
    ]
