# Generated by Django 6.0.4 on 2026-04-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0002_add_catalog_url_to_remote_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteitem',
            name='raw_jsonld',
            field=models.JSONField(blank=True, null=True, verbose_name='Raw JSON-LD'),
        ),
    ]
