import { createContext, ReactNode, useCallback, useContext, useMemo, useState } from 'react';

const LANGUAGES = ['en', 'de'] as const;
export type Language = (typeof LANGUAGES)[number];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  /** Apply a language coming from an external source (e.g. profile API)
   *  without triggering a save-back. */
  syncLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Header
    'header.search': 'Search items in your community...',
    'header.shareItem': 'Share Item',
    'header.signIn': 'Sign In',
    'header.myProfile': 'Profile',
    'header.items': 'Items',
    'header.requests': 'Requests',
    'header.signOut': 'Sign Out',
    'header.theme': 'Theme',
    'header.light': 'Light',
    'header.dark': 'Dark',

    // Search bar / facets
    'search.filterBy': 'Filter by',
    'search.type': 'Type',
    'search.owner': 'Owner',
    'search.collection': 'Collection',
    'search.category': 'Category',
    'search.availability': 'Availability',
    'search.searchOwners': 'Search people…',
    'search.searchCollections': 'Search collections…',
    'search.searchCategories': 'Search categories…',
    'search.noResults': 'No matches',
    'search.loading': 'Loading…',
    'search.availability.available': 'Available',
    'search.availability.rented': 'Rented',
    'search.availability.sold': 'Sold',
    'search.removeFilter': 'Remove filter',
    'search.close': 'Close search',
    'search.price': 'Price',
    'search.price.min': 'Min',
    'search.price.max': 'Max',
    'search.price.free': 'Free',
    'search.price.freeOnly': 'Free only',

    // Auth
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.loginRequired': 'Please log in to book or buy this item',
    // Auth page specific
    'auth.backToHome': 'Back to Home',
    'auth.welcomeTitle': 'Welcome to Bubble',
    'auth.signInSubtitle': 'Sign in to your account',
    'auth.orContinueWith': 'Or continue with',
    'auth.usernameOrEmail': 'Username or Email',
    'auth.enterUsernameOrEmail': 'Enter your username or email',
    'auth.enterPassword': 'Enter your password',
    'auth.signingIn': 'Signing in...',
    'auth.noAccountContact': "Don't have an account? Contact your administrator.",
    'auth.welcomeBackTitle': 'Welcome back!',
    'auth.loggedInAs': 'Logged in successfully as',
    'auth.loginFailed': 'Login failed. Please check your credentials.',
    'auth.unexpectedError': 'An unexpected error occurred. Please try again.',

    // Index Page
    'index.itemsFound': '{count} items found',
    'index.loadingItems': 'Loading items...',
    'index.noItemsFound': 'No items found in this category.',
    'index.condition': 'Condition',
    'index.sortBy': 'Sort by',
    'index.sort': 'Sort',
    'index.sortName': 'Name',
    'index.sortPrice': 'Price',
    'index.filterAndSort': 'Filter and sort',
    'index.scopeLocal': 'Local',
    'index.scopeAll': 'All',
    'index.scopeFederated': 'Federated',
    'index.scope': 'Scope',
    'index.sortDate': 'Date',

    // Browse Nav
    'browse.buy': 'Donate/Sell',
    'browse.rent': 'Borrow/Rent',
    'browse.wanted': 'Wanted',

    // Items
    'item.available': 'Available',
    'item.unavailable': 'Unavailable',
    'item.messageOwner': 'Message',
    'item.category': 'Category',
    'item.condition': 'Condition',
    'item.location': 'Location',
    'item.cannotMessageSelf': 'This is already yours',
    'item.name': 'Name',
    'item.price': 'Price',
    'item.createdAt': 'Date',

    // List Item
    'editItem.title': 'Share an Item',
    'editItem.name': 'Item Name',
    'editItem.itemName': 'Item Name',
    'editItem.itemNamePlaceholder': 'Enter the name of your item...',
    'editItem.enterName': 'Enter the item name...',
    'editItem.description': 'Description',
    'editItem.enterDescription': 'Enter a description for your item...',
    'editItem.descriptionPlaceholder': 'Describe your item, its condition, and any details...',
    'editItem.category': 'Category',
    'editItem.condition': 'Condition',
    'editItem.status': 'Status',
    'editItem.selectCategory': 'Select Category',
    'editItem.selectCondition': 'Select Condition',
    'editItem.selectStatus': 'Select Status',
    'editItem.salePrice': 'Sale Price',
    'editItem.rentalPrice': 'Rental Price',
    'editItem.price': 'Price',
    'editItem.pricingModel': 'Sell or Rent',
    'editItem.sell': 'Sell',
    'editItem.rent': 'Rent',
    'editItem.enterPrice': 'Enter price',
    'editItem.enterSalePrice': 'Enter sale price',
    'editItem.enterRentalPrice': 'Enter rental price',
    'editItem.rentalPeriod': 'Rental Period',
    'editItem.selectRentalPeriod': 'Select Rental Period',
    'editItem.rentalOptions': 'Rental Options',
    'editItem.rentalSelfService': 'Allow self-service rental (no approval required)',
    'editItem.rentalOpenEnd': 'Allow open-ended rental (no return date)',
    'editItem.uploadImages': 'Upload Images',
    'editItem.shareItem': 'Share Item',
    'editItem.listItem': 'List Item',
    'editItem.publish': 'Publish',
    'editItem.aiMagic': 'AI Magic',
    'editItem.aiMagicProcessing': 'Processing...',
    'editItem.aiMagicWarningTitle': 'AI Magic - Data Override Warning',
    'editItem.aiMagicWarningDescription':
      'AI Magic will analyze your images and automatically update the item name, description, category, and price. This may overwrite your existing data. Do you want to continue?',
    'editItem.aiMagicWarningCancel': 'Cancel',
    'editItem.aiMagicWarningContinue': 'Continue',
    'editItem.incompleteWarningTitle': 'Incomplete Item',
    'editItem.incompleteWarningDescription': 'This item is missing some required information:',
    'editItem.stayAndComplete': 'Stay and Complete',
    'editItem.leaveAnyway': 'Leave Anyway',
    'editItem.aiMagicImage': 'Generate Image',
    'editItem.scanIsbn': 'Scan ISBN',
    'editItem.refetchIsbn': 'Re-fetch ISBN',
    'editItem.visibility': 'Visibility',
    'editItem.selectVisibility': 'Select Visibility',
    'editItem.accessSection': 'Visibility & Access',

    // Visibility
    'visibility.public': 'Public',
    'visibility.authenticated': 'Authenticated Users',
    'visibility.specific': 'Specific Users / Groups',
    'visibility.private': 'Private',

    // Access Manager
    'accessManager.title': 'Access Management',
    'accessManager.coOwnersTitle': 'Co-owners',
    'accessManager.coOwnersDescription': 'Co-owners can edit and manage bookings for this item.',
    'accessManager.viewersTitle': 'Specific Viewers',
    'accessManager.viewersDescription': 'These users and groups can view this item.',
    'accessManager.users': 'Users',
    'accessManager.groups': 'Groups',
    'accessManager.addUser': 'Add User',
    'accessManager.searchUsers': 'Search users...',
    'accessManager.addGroup': 'Add Group',
    'accessManager.searchGroups': 'Search groups...',

    // Categories
    'categories.all': 'All Categories',
    'categories.electronics': 'Electronics',
    'categories.furniture': 'Furniture',
    'categories.books': 'Books',
    'categories.clothing': 'Clothing',
    'categories.sports': 'Sports',
    'categories.tools': 'Tools',
    'categories.kitchen': 'Kitchen',
    'categories.garden': 'Garden',
    'categories.toys': 'Toys',
    'categories.vehicles': 'Vehicles',
    'categories.rooms': 'Rooms',
    'categories.other': 'Other',

    // Conditions
    'condition.new': 'New',
    'condition.used': 'Used',
    'condition.broken': 'Broken',
    'condition.unknown': 'Unknown',

    // Item UI
    'item.noImage': 'No image',
    'item.listingType.sell': 'Sell',
    'item.listingType.rent': 'Rent',
    'item.listingType.sellRent': 'Sell/Rent',
    'item.salesType.label': 'Listing type',
    'item.salesType.sell': 'Sell',
    'item.salesType.donate': 'Donate',
    'item.salesType.rent': 'Rent out',
    'item.salesType.borrow': 'Lend (free borrow)',
    'item.salesType.want_buy': 'Wanted — looking to buy',
    'item.salesType.want_rent': 'Wanted — looking to rent',
    'item.salesType.badge.sell': 'For Sale',
    'item.salesType.badge.donate': 'Free',
    'item.salesType.badge.rent': 'For Rent',
    'item.salesType.badge.borrow': 'Borrow',
    'item.salesType.badge.want_buy': 'Wanted',
    'item.salesType.badge.want_rent': 'Wanted (rent)',
    'item.instantRental': 'Instant Rental',
    'item.instantRentalTooltip':
      'This item can be rented immediately without waiting for owner confirmation.',
    'item.price.sale': 'sale',
    'item.price.rent': 'rent',
    // Time
    'time.hour': 'hour',
    'time.hours': 'hours',
    'time.perHour': '/h',
    'time.perDay': '/d',
    'time.perWeek': '/w',
    // EditItem UI
    'editItem.uploadNewImages': 'Upload new Images',
    'editItem.clearNewImages': 'Clear New Images',
    'editItem.uploadingImages': 'Uploading new images...',
    'editItem.aiProcessing': 'AI is analyzing your images and updating content...',
    'editItem.processingCompleted': 'Processing complete!',
    'editItem.processingError': 'An error occurred during processing.',
    'editItem.saleDisabledPlaceholder': 'Leave empty to disable sale',
    'editItem.rentalDisabledPlaceholder': 'Leave empty to disable rental',
    'editItem.saleDisablesRental': 'Setting a sale price disables rental price',
    'editItem.rentalDisablesSale': 'Setting a rental price disables sale price',
    'editItem.primaryBadge': 'Primary',
    // Image Upload Step
    'imageUpload.title': 'Upload Item Images',
    'imageUpload.description': 'Add photos of your item to help others find and understand it.',
    'imageUpload.imagesUploaded': 'image uploaded',
    'imageUpload.imagesUploadedPlural': 'images uploaded',
    'imageUpload.aiGenerating': 'Generating AI content…',
    'imageUpload.continueWithAI': 'Continue with AI Processing',
    'imageUpload.skipAndContinue': 'Skip AI, Continue Manually',
    'imageUpload.scanIsbn': 'Scan Book ISBN',
    'imageUpload.scanIsbnDescription':
      'Scan a book barcode to create a new book entry automatically',
    'imageUpload.scanIsbnCreating': 'Creating book from ISBN…',
    'imageUpload.scanIsbnSuccessTitle': 'Book Created',
    'imageUpload.scanIsbnSuccessDescription':
      'Book details fetched from ISBN. You can now edit the details.',
    'imageUpload.scanIsbnErrorTitle': 'ISBN Scan Failed',
    'imageUpload.scanIsbnErrorDescription': 'Failed to create book from ISBN. Please try again.',

    // ImageManager UI text
    'imageManager.uploadInstructions':
      'Upload up to {max} images. The first image will be used as the primary image.{drag}',
    'imageManager.dragToReorder': '(Drag to reorder)',
    'imageManager.imagesLabel': 'Images',

    // ImageManager
    'imageManager.tooManyTitle': 'Too many images',
    'imageManager.tooManyDescription': 'Maximum {max} images allowed',
    'imageManager.invalidTypeTitle': 'Invalid file type',
    'imageManager.invalidTypeDescription': 'Please select only image files',
    'imageManager.fileTooLargeTitle': 'File too large',
    'imageManager.fileTooLargeDescription': 'Images must be smaller than 20MB',
    'imageManager.deleteSuccessTitle': 'Success',
    'imageManager.deleteSuccessDescription': 'Image deleted successfully',
    'imageManager.deleteErrorTitle': 'Error',
    'imageManager.deleteErrorDescription': 'Failed to delete image',
    'imageManager.rotateErrorTitle': 'Error',
    'imageManager.rotateErrorDescription': 'Failed to rotate image',
    'imageManager.rotateLeft': 'Rotate left',
    'imageManager.rotateRight': 'Rotate right',

    // Requests
    'requests.title': 'Requests',
    'requests.noConversations': 'No conversations yet',
    'requests.startConversation': 'Start a conversation by messaging someone about their item!',
    'requests.typeMessage': 'Type a message...',
    'requests.send': 'Send',
    'requests.selectConversation': 'Select a conversation to start messaging',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.loadingError': 'Error while loading',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.saving': 'Saving...',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.update': 'Update',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submitting': 'Submitting...',

    // Booking
    'booking.bookNow': 'Book Now',
    'booking.createBooking': 'Create Booking Request',
    'booking.createBookingDescription': 'Submit a booking request for {itemName}',
    'booking.purchaseOffer': 'Your Purchase Offer',
    'booking.rentalOffer': 'Your Rental Offer',
    'booking.totalPrice': 'Total Price',
    'booking.listedPrice': 'Listed Price',
    'booking.listedRentalPrice': 'Listed Rental Price',
    'booking.enterYourOffer': 'Enter your offer amount',
    'booking.rentalStart': 'Rental Start Date & Time',
    'booking.rentalEnd': 'Rental End Date & Time',
    'booking.rentalEndOptional': 'End Date & Time',
    'booking.rentalEndOptionalNote': 'No end date required — leave blank for an open-ended rental.',
    'booking.submitRequest': 'Submit Request',
    'booking.successTitle': 'Success',
    'booking.successCreated': 'Booking request created successfully!',
    'booking.errorCreate': 'Failed to create booking request. Please try again.',
    'booking.successUpdated': 'Booking updated successfully!',
    'booking.errorUpdate': 'Failed to update booking. Please try again.',
    'requests.acceptWarningTitle': 'Confirm acceptance',
    'requests.acceptWarningDescription':
      'You are accepting an offer of {amount}. This will be finalized when the request is confirmed.',

    // Calendar
    'calendar.selectRentalPeriod': 'Select Rental Period',
    'calendar.time': 'Time',
    'calendar.clickToComplete': 'Click another time slot to complete selection',
    'calendar.selectedPeriod': 'Selected Period',
    'calendar.from': 'From',
    'calendar.to': 'To',
    'calendar.duration': 'Duration',
    'calendar.hours': 'hours',
    'calendar.days': 'days',
    'calendar.selectingPeriod': 'Selecting period',
    'calendar.clickToSetEnd': 'Click an end tile to confirm, or hover to preview',
    'calendar.clearSelection': 'Clear',
    'calendar.week': 'Week',
    'calendar.month': 'Month',

    // Requests Page
    'requests.allBookings': 'All Requests',
    'requests.noBookings': 'No requests yet',
    'requests.selectBooking': 'Select a request to view details',
    'requests.bookingDetails': 'Request Details',
    'requests.bookingItem': 'Request',
    'requests.unknownItem': 'Unknown Item',
    'requests.user': 'User',
    'requests.bookingId': 'Request ID',
    'requests.itemId': 'Item ID',
    'requests.requestFrom': 'Request from',
    'requests.requestTo': 'Request to',
    'requests.offerAmount': 'Offer Amount',
    'requests.counterOffer': 'Counter Offer',
    'requests.rentalPeriod': 'Rental Period',
    'requests.noDate': 'No date specified',
    'requests.accept': 'Accept',
    'requests.acceptCounterOffer': 'Accept counteroffer',
    'requests.reject': 'Reject',
    'requests.cancel': 'Cancel Request',
    'requests.noMessages': 'No messages yet',
    'requests.startConversation': 'Start the conversation by sending a message',
    'requests.messagesComingSoon': 'Messages feature coming soon',
    'requests.messagesDescription': 'You will be able to chat about requests here',
    'requests.typeMessage': 'Type a message...',
    'requests.messages': 'Messages',
    'requests.refresh': 'Refresh',
    'requests.refreshing': 'Refreshing...',
    'requests.editBooking': 'Edit Request',
    'requests.editBookingDescription': 'Edit rental period or offered price for this request.',
    'requests.update': 'Update',
    'requests.counterOfferDialogTitle': 'Make a counter offer',
    'requests.counterOfferDialogDescription':
      'Enter an alternative price to propose for this request.',
    'requests.counterOfferSubmit': 'Submit Counter Offer',
    'requests.status.pending': 'Pending',
    'requests.status.cancelled': 'Cancelled',
    'requests.status.confirmed': 'Confirmed',
    'requests.status.accepted': 'Accepted',
    'requests.status.rejected': 'Rejected',
    'requests.status.completed': 'Completed',
    'requests.status.unknown': 'Unknown',

    // Bookings page
    'bookings.title': 'My Bookings',
    'bookings.noBookings': 'No bookings found',
    'bookings.gridView': 'Grid view',
    'bookings.listView': 'List view',
    'bookings.filterAll': 'All',
    'bookings.filterOwner': 'My items',
    'bookings.filterRenter': 'Items I booked',
    'bookings.active': 'Active',
    'bookings.upcoming': 'Upcoming',
    'bookings.past': 'Past',
    'bookings.timeBooked': 'Time booked',
    'bookings.cost': 'Cost',
    'bookings.dateFrom': 'From',
    'bookings.dateTo': 'To',
    'bookings.dateRangeLabel': 'Date range',
    'bookings.ongoing': 'Ongoing',
    'bookings.user': 'User',
    'bookings.item': 'Item',
    'bookings.status': 'Status',
    'bookings.filterDateFrom': 'From date',
    'bookings.filterDateTo': 'To date',
    'bookings.resetFilters': 'Reset filters',
    'bookings.endBooking': 'End booking',
    'bookings.prevPeriod': 'Previous period',
    'bookings.nextPeriod': 'Next period',
    'bookings.today': 'Today',
    'bookings.searchPlaceholder': 'Search bookings by item or person…',
    'bookings.showPending': 'Show pending requests',
    'bookings.pending': 'Pending',
    'bookings.directionPast': 'Past',
    'bookings.directionUpcoming': 'Current & upcoming',
    'bookings.perPage': 'Per page',
    'bookings.noSearchResults': 'No bookings match your search',
    'bookings.searchingAll': 'Searching all bookings — past, current & upcoming',
    'header.bookings': 'Bookings',

    // Item Detail
    'itemDetail.backToItems': 'Back to Items',
    'itemDetail.editItem': 'Edit Item',
    'itemDetail.deleteItem': 'Delete Item',
    'itemDetail.contactOwner': 'Contact Owner',
    'itemDetail.buyNow': 'Buy',
    'itemDetail.rentNow': 'Rent',
    'itemDetail.borrowNow': 'Borrow',
    'itemDetail.requestDonate': 'Request',
    'itemDetail.itemDetails': 'Item Details',
    'itemDetail.description': 'Description',
    'itemDetail.listed': 'Listed',
    'itemDetail.location': 'Location',
    'itemDetail.ownerInfo': 'Owner Information',
    'itemDetail.deleteConfirmTitle': 'Are you sure?',
    'itemDetail.deleteConfirmDescription':
      'This action cannot be undone. This will permanently delete your item.',
    'itemDetail.notFound': 'Item not found',
    'itemDetail.availability': 'Availability',
    'itemDetail.properties': 'Properties',
    'itemDetail.previousImage': 'Previous image',
    'itemDetail.nextImage': 'Next image',
    'itemDetail.openImage': 'Open image in full screen',
    'itemDetail.closeViewer': 'Close image viewer',
    'itemDetail.goToImage': 'Go to image',

    // My Items
    'myItems.title': 'My Items',
    'myItems.noItems': 'No items yet',
    'myItems.createFirst': 'Create your first item to get started!',
    'myItems.shareItem': 'Share Item',
    'myItems.status': 'Status',
    'myItems.changeStatus': 'Change Status',
    'myItems.statusUpdated': 'Item status updated successfully',

    // Item Status
    'status.draft': 'Draft',
    'status.available': 'Available',
    'status.reserved': 'Reserved',
    'status.rented': 'Rented',
    'status.sold': 'Gone',
    'status.unknown': 'Unknown',
    // Profile
    'profile.title': 'Profile Settings',
    'profile.manage': 'Manage your profile information',
    'profile.name': 'Name',
    'profile.phone': 'Phone',
    'profile.bio': 'Bio',
    'profile.address': 'Address',
    'profile.emailReminder': 'Email reminders',
    'profile.emailReminderDesc': 'Receive email reminders for bookings and messages',
    'profile.notifications': 'Notifications',
    'profile.notificationsDesc': 'Configure external notification channels',
    'profile.rocketchatNewMessage': 'New message via RocketChat',
    'profile.rocketchatNewMessageDesc':
      'Receive a RocketChat notification when you get a new message in Bubble',
    'profile.appearance': 'Appearance',
    'profile.themeAuto': 'Auto',
    'profile.language': 'Language',
    'profile.username': 'Username',
    'profile.email': 'Email',
    'profile.readOnly': 'Read-only',
    'profile.update': 'Update Profile',
    'profile.updating': 'Updating profile...',
    'editItem.invalidPricingTitle': 'Invalid Pricing',
    'editItem.invalidPricingDescription':
      'Please set either a sale price or a rental price, not both.',
    'editItem.updateSuccessTitle': 'Item Updated',
    'editItem.updateSuccessDescription': 'Your item has been updated successfully.',
    'editItem.updateErrorTitle': 'Update Failed',
    'editItem.updateErrorDescription': 'Failed to update item. Please try again.',
    'editItem.publishSuccessTitle': 'Item Published',
    'editItem.publishSuccessDescription': 'Your item is now available to the community.',
    'editItem.isbnUpdateSuccessTitle': 'Book Updated from ISBN',
    'editItem.isbnUpdateSuccessDescription':
      'Book details have been fetched and updated from OpenLibrary.',
    'editItem.isbnUpdateErrorTitle': 'ISBN Update Failed',
    'editItem.isbnUpdateErrorDescription':
      'Failed to fetch book data from OpenLibrary. Please try again.',
    'editItem.isbnInvalidErrorTitle': 'Invalid ISBN',
    'editItem.isbnInvalidErrorDescription':
      'The ISBN you entered is not valid. Please check the format and try again.',
    'editItem.images': 'Images',
    'editItem.editBook': 'Edit Book',
    'editItem.bookDetails': 'Book Details',
    'editItem.isbn': 'ISBN',
    'editItem.enterIsbn': 'Enter ISBN',
    'editItem.year': 'Publication Year',
    'editItem.enterYear': 'Enter year',
    'editItem.topic': 'Topic',
    'editItem.enterTopic': 'Enter topic or subject',
    'editItem.authors': 'Authors',
    'editItem.selectAuthors': 'Select authors',
    'editItem.enterAuthors': 'Enter authors (comma separated)',
    'editItem.genres': 'Genres',
    'editItem.selectGenres': 'Select genres',
    'editItem.enterGenres': 'Enter genres (comma separated)',
    'editItem.publisher': 'Publisher',
    'editItem.selectPublisher': 'Select publisher',
    'editItem.enterPublisher': 'Enter publisher',
    'editItem.shelf': 'Shelf',
    'editItem.selectShelf': 'Select shelf location',
    'editItem.enterShelf': 'Enter shelf location',
    'editItem.location': 'Location',
    'editItem.selectLocation': 'Select location',
    'editItem.locationOwnerPlace': "At the owner's place",
    'editItem.locationLoading': 'Loading locations…',
    'rentalPeriod.h': 'Hourly',
    'rentalPeriod.d': 'Daily',
    'rentalPeriod.w': 'Weekly',
    // User labels
    'user.name': 'Name',
    'user.email': 'Email',
    // Scanner
    'scanner.open': 'Open scanner',
    'scanner.title': 'Scan Barcode',
    'scanner.description': 'Position the barcode within the camera view to scan',
    'scanner.usingNative': 'Using native BarcodeDetector',
    'scanner.usingPolyfill': 'Using barcode-detector polyfill',
    'scanner.initializingCamera': 'Initializing camera...',
    'scanner.detected': 'Detected',

    // Collections
    'collections.title': 'Collections',
    'collections.myCollections': 'My Collections',
    'collections.newCollection': 'New Collection',
    'collections.newCollectionShort': 'New',
    'collections.createCollection': 'Create Collection',
    'collections.name': 'Name',
    'collections.namePlaceholder': 'e.g. Weekend Camping Gear',
    'collections.slug': 'Slug',
    'collections.slugPlaceholder': 'e.g. weekend-camping-gear',
    'collections.slugHelp': 'Used in the collection URL. Generated from the name by default.',
    'collections.description': 'Description',
    'collections.descriptionPlaceholder': 'What is this collection for?',
    'collections.itemCount': '{count} items',
    'collections.noCollections': 'No collections yet. Create your first one!',
    'collections.noItems': 'No items in this collection yet.',
    'collections.addToCollection': 'Add to collection',
    'collections.removeFromCollection': 'Remove from collection',
    'collections.addedToCollection': 'Added to collection',
    'collections.removedFromCollection': 'Removed from collection',
    'collections.deleteCollection': 'Delete collection',
    'collections.confirmDelete':
      'Are you sure you want to delete this collection? This cannot be undone.',
    'collections.editCollection': 'Edit collection',
    'collections.saveChanges': 'Save changes',
    'collections.permissions': 'Sharing & Permissions',
    'collections.shareCollection': 'Share collection',
    'collections.grantAccess': 'Grant access',
    'collections.grantPermission': 'Share',
    'collections.revokePermission': 'Revoke',
    'collections.username': 'Username',
    'collections.usernamePlaceholder': 'Enter username',
    'collections.permission': 'Permission',
    'collections.action': 'Action',
    'collections.backToCollections': 'Back to Collections',
    'collections.owner': 'Owner',
    'collections.created': 'Created',
    'collections.header.myCollections': 'My Collections',
    'collections.permissionsTab': 'Permissions',
    'collections.detailsTab': 'Details',
    'collections.subjectTypeUser': 'User',
    'collections.subjectTypeGroup': 'Group',
    'collections.groupName': 'Group',
    'collections.groupPlaceholder': 'Search groups...',
    'collections.history': 'Collection History',
    'collections.historyButton': 'History',
    'collections.historyEmpty': 'No events recorded yet.',
    'collections.historyAdded': 'Added',
    'collections.historyRemoved': 'Removed',
    'collections.historyBy': 'by',
    'collections.appearsIn': 'Appears in collections',
    'collections.appearsInNone': 'Not in any collection',
    'collections.currentGrants': 'Current permissions',
    'collections.noGrants': 'No permissions granted yet.',
    'collections.grantSubject': 'User / Group',
    'collections.grantPermissionCol': 'Permission',
    'collections.grantType': 'Type',
    'collections.permUser': 'User',
    'collections.permGroup': 'Group',
    'collections.roleView': 'View',
    'collections.roleEdit': 'Edit',
    'collections.roleOwner': 'Owner',
    'collections.revokeGrant': 'Revoke',
    'collections.ownerCannotRevoke': 'Cannot remove permissions from the collection creator',
    'collections.searchPlaceholder': 'Search collections...',
    'collections.onlyMine': 'Only mine',
    'collections.viewList': 'List view',
    'collections.viewGrid': 'Grid view',

    // Calendar subscription (CalDAV / iCalendar)
    'calendar.title': 'Calendar subscription',
    'calendar.item.description':
      'Share a private link to subscribe to this item’s bookings in any calendar app that supports iCalendar. Pending bookings appear as tentative, confirmed ones as busy.',
    'calendar.collection.description':
      'Subscribe to all bookings of this collection in your calendar app. Each entry shows the booked item and who booked it.',
    'calendar.personal.title': 'Your personal booking calendar',
    'calendar.personal.description':
      'Add this private CalDAV calendar to your calendar app to see availability of bookable items. Creating an event in an item’s calendar sends a booking request for that time.',
    'calendar.copy': 'Copy link',
    'calendar.copied': 'Link copied to clipboard',
    'calendar.subscribe': 'Subscribe',
    'calendar.subscribeTooltip': 'Subscribe to calendar',
    'calendar.regenerate': 'Regenerate link',
    'calendar.regenerateConfirm':
      'Generate a new link? The current link will stop working immediately.',
    'calendar.regenerated': 'A new calendar link was generated',
    'calendar.revoke': 'Disable',
    'calendar.revoked': 'Calendar link disabled',
    'calendar.show': 'Show calendar link',
    'calendar.hide': 'Hide',
    'calendar.secretHint': 'Anyone with this link can view the calendar — keep it private.',
    'calendar.loadError': 'Could not load the calendar link.',
  },
  de: {
    // Header
    'header.search': 'Suche Artikel in deiner Community...',
    'header.shareItem': 'Artikel teilen',
    'header.signIn': 'Anmelden',
    'header.myProfile': 'Profil',
    'header.items': 'Artikel',
    'header.requests': 'Anfragen',
    'header.signOut': 'Abmelden',
    'header.theme': 'Design',
    'header.light': 'Hell',
    'header.dark': 'Dunkel',

    // Search bar / facets
    'search.filterBy': 'Filtern nach',
    'search.type': 'Typ',
    'search.owner': 'Anbieter',
    'search.collection': 'Sammlung',
    'search.category': 'Kategorie',
    'search.availability': 'Verfügbarkeit',
    'search.searchOwners': 'Personen suchen…',
    'search.searchCollections': 'Sammlungen suchen…',
    'search.searchCategories': 'Kategorien suchen…',
    'search.noResults': 'Keine Treffer',
    'search.loading': 'Wird geladen…',
    'search.availability.available': 'Verfügbar',
    'search.availability.rented': 'Vermietet',
    'search.availability.sold': 'Verkauft',
    'search.removeFilter': 'Filter entfernen',
    'search.close': 'Suche schließen',
    'search.price': 'Preis',
    'search.price.min': 'Min',
    'search.price.max': 'Max',
    'search.price.free': 'Gratis',
    'search.price.freeOnly': 'Nur gratis',

    // Auth
    'auth.signIn': 'Anmelden',
    'auth.signUp': 'Registrieren',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.confirmPassword': 'Passwort bestätigen',
    'auth.forgotPassword': 'Passwort vergessen?',
    'auth.noAccount': 'Noch kein Konto?',
    'auth.hasAccount': 'Bereits ein Konto?',
    'auth.loginRequired': 'Bitte melde dich an, um diesen Artikel zu buchen oder zu kaufen',
    // Auth page specific
    'auth.backToHome': 'Zurück zur Startseite',
    'auth.welcomeTitle': 'Willkommen bei Bubble',
    'auth.signInSubtitle': 'Melde dich bei deinem Konto an',
    'auth.orContinueWith': 'Oder fortfahren mit',
    'auth.usernameOrEmail': 'Benutzername oder E-Mail',
    'auth.enterUsernameOrEmail': 'Gib deinen Benutzernamen oder deine E-Mail ein',
    'auth.enterPassword': 'Gib dein Passwort ein',
    'auth.signingIn': 'Anmeldung...',
    'auth.noAccountContact': 'Noch kein Konto? Kontaktiere deinen Administrator.',
    'auth.welcomeBackTitle': 'Willkommen zurück!',
    'auth.loggedInAs': 'Erfolgreich eingeloggt als',
    'auth.loginFailed': 'Anmeldung fehlgeschlagen. Bitte überprüfe deine Zugangsdaten.',
    'auth.unexpectedError': 'Ein unerwarteter Fehler ist aufgetreten. Bitte versuche es erneut.',

    // Index Page
    'index.itemsFound': '{count} Artikel gefunden',
    'index.loadingItems': 'Artikel werden geladen...',
    'index.noItemsFound': 'Keine Artikel in dieser Kategorie gefunden.',
    'index.condition': 'Zustand',
    'index.sortBy': 'Sortieren nach',
    'index.sort': 'Sortierung',
    'index.sortName': 'Name',
    'index.sortPrice': 'Preis',
    'index.filterAndSort': 'Filtern und sortieren',
    'index.sortDate': 'Datum',
    'index.scope': 'Bereich',
    'index.scopeLocal': 'Lokal',
    'index.scopeAll': 'Alle',
    'index.scopeFederated': 'Föderiert',

    // Browse Nav
    'browse.buy': 'Verschenken/Verkaufen',
    'browse.rent': 'Leihen/Mieten',
    'browse.wanted': 'Gesucht',

    // Items
    'item.available': 'Verfügbar',
    'item.unavailable': 'Nicht verfügbar',
    'item.messageOwner': 'Nachricht',
    'item.category': 'Kategorie',
    'item.condition': 'Zustand',
    'item.location': 'Ort',
    'item.cannotMessageSelf': 'Der Artikel gehört schon dir',
    'item.name': 'Name',
    'item.price': 'Preis',
    'item.createdAt': 'Datum',

    // List Item
    'editItem.title': 'Artikel teilen',
    'editItem.name': 'Artikelname',
    'editItem.itemName': 'Artikelname',
    'editItem.itemNamePlaceholder': 'Gib den Namen deines Artikels ein...',
    'editItem.enterName': 'Artikelnamen eingeben...',
    'editItem.description': 'Beschreibung',
    'editItem.saleDisablesRental':
      'Wenn du einen Verkaufspreis setzt, ist der Mietpreis deaktiviert',
    'editItem.rentalDisablesSale':
      'Wenn du einen Mietpreis setzt, ist der Verkaufspreis deaktiviert',
    'editItem.enterDescription': 'Beschreibung für den Artikel...',
    'editItem.descriptionPlaceholder':
      'Beschreibe deinen Artikel, seinen Zustand und weitere Details...',
    'editItem.category': 'Kategorie',
    'editItem.condition': 'Zustand',
    'editItem.status': 'Status',
    'editItem.selectCategory': 'Kategorie auswählen',
    'editItem.selectCondition': 'Zustand auswählen',
    'editItem.selectStatus': 'Status auswählen',
    'editItem.salePrice': 'Verkaufspreis',
    'editItem.rentalPrice': 'Mietpreis',
    'editItem.price': 'Preis',
    'editItem.pricingModel': 'Verkaufen oder Vermieten',
    'editItem.sell': 'Verkaufen',
    'editItem.rent': 'Vermieten',
    'editItem.enterPrice': 'Preis eingeben',
    'editItem.enterSalePrice': 'Verkaufspreis eingeben',
    'editItem.enterRentalPrice': 'Mietpreis eingeben',
    'editItem.rentalPeriod': 'Mietzeitraum',
    'editItem.selectRentalPeriod': 'Mietzeitraum auswählen',
    'editItem.rentalOptions': 'Miet Optionen',
    'editItem.rentalSelfService': 'Selbstbedienung erlauben (keine Genehmigung nötig)',
    'editItem.rentalOpenEnd': 'Offene Miete erlauben (kein Rückgabedatum)',
    'editItem.uploadImages': 'Bilder hochladen',
    'editItem.shareItem': 'Artikel teilen',
    'editItem.listItem': 'Artikel einstellen',
    'editItem.publish': 'Veröffentlichen',
    'editItem.aiMagic': 'KI Magie',
    'editItem.aiMagicProcessing': 'Wird verarbeitet...',
    'editItem.aiMagicWarningTitle': 'KI Magie - Datenüberschreibungswarnung',
    'editItem.aiMagicWarningDescription':
      'KI Magie analysiert deine Bilder und aktualisiert automatisch den Artikelnamen, die Beschreibung, die Kategorie und den Preis. Dies kann deine vorhandenen Daten überschreiben. Möchtest du fortfahren?',
    'editItem.aiMagicWarningCancel': 'Abbrechen',
    'editItem.aiMagicWarningContinue': 'Fortfahren',
    'editItem.incompleteWarningTitle': 'Unvollständiger Artikel',
    'editItem.incompleteWarningDescription':
      'Diesem Artikel fehlen einige erforderliche Informationen:',
    'editItem.stayAndComplete': 'Bleiben und vervollständigen',
    'editItem.leaveAnyway': 'Trotzdem verlassen',
    'editItem.aiMagicImage': 'Bild generieren',
    'editItem.scanIsbn': 'ISBN scannen',
    'editItem.refetchIsbn': 'ISBN neu abrufen',
    'editItem.visibility': 'Sichtbarkeit',
    'editItem.selectVisibility': 'Sichtbarkeit auswählen',
    'editItem.accessSection': 'Sichtbarkeit & Zugriff',

    // Visibility
    'visibility.public': 'Öffentlich',
    'visibility.authenticated': 'Angemeldete Nutzer',
    'visibility.specific': 'Bestimmte Nutzer / Gruppen',
    'visibility.private': 'Privat',

    // Access Manager
    'accessManager.title': 'Zugriffsverwaltung',
    'accessManager.coOwnersTitle': 'Mitbesitzer',
    'accessManager.coOwnersDescription':
      'Mitbesitzer können diesen Artikel bearbeiten und Buchungen verwalten.',
    'accessManager.viewersTitle': 'Bestimmte Betrachter',
    'accessManager.viewersDescription': 'Diese Nutzer und Gruppen können den Artikel sehen.',
    'accessManager.users': 'Nutzer',
    'accessManager.groups': 'Gruppen',
    'accessManager.addUser': 'Nutzer hinzufügen',
    'accessManager.searchUsers': 'Nutzer suchen...',
    'accessManager.addGroup': 'Gruppe hinzufügen',
    'accessManager.searchGroups': 'Gruppen suchen...',

    // Categories
    'categories.all': 'Alle Kategorien',
    'categories.electronics': 'Elektronik',
    'categories.furniture': 'Möbel',
    'categories.books': 'Bücher',
    'categories.clothing': 'Kleidung',
    'categories.sports': 'Sport',
    'categories.tools': 'Werkzeuge',
    'categories.kitchen': 'Küche',
    'categories.garden': 'Garten',
    'categories.toys': 'Spielzeug',
    'categories.vehicles': 'Fahrzeuge',
    'categories.rooms': 'Räume',
    'categories.other': 'Sonstiges',

    // Conditions
    'condition.new': 'Neu',
    'condition.used': 'Gebraucht',
    'condition.broken': 'Kaputt',
    'condition.unknown': 'Unbekannt',

    // Item UI
    'item.noImage': 'Kein Bild',
    'item.listingType.sell': 'Verkaufen',
    'item.listingType.rent': 'Mieten',
    'item.listingType.sellRent': 'Verkaufen/Mieten',
    'item.salesType.label': 'Angebotstyp',
    'item.salesType.sell': 'Verkaufen',
    'item.salesType.donate': 'Verschenken',
    'item.salesType.rent': 'Vermieten',
    'item.salesType.borrow': 'Verleihen (kostenlos)',
    'item.salesType.want_buy': 'Gesucht — kaufen',
    'item.salesType.want_rent': 'Gesucht — mieten',
    'item.salesType.badge.sell': 'Zu verkaufen',
    'item.salesType.badge.donate': 'Kostenlos',
    'item.salesType.badge.rent': 'Zu vermieten',
    'item.salesType.badge.borrow': 'Zum Ausleihen',
    'item.salesType.badge.want_buy': 'Gesucht',
    'item.salesType.badge.want_rent': 'Gesucht (Miete)',
    'item.instantRental': 'Sofortmiete',
    'item.instantRentalTooltip':
      'Dieser Artikel kann sofort gemietet werden, ohne auf die Bestätigung des Besitzers zu warten.',
    'item.price.sale': 'Verkauf',
    'item.price.rent': 'Miete',
    // Time
    'time.hour': 'Stunde',
    'time.hours': 'Stunden',
    'time.perHour': '/h',
    'time.perDay': '/d',
    'time.perWeek': '/w',
    // EditItem UI
    'editItem.uploadNewImages': 'Neue Bilder hochladen',
    'editItem.clearNewImages': 'Neue Bilder löschen',
    'editItem.uploadingImages': 'Lade neue Bilder hoch...',
    'editItem.aiProcessing': 'KI analysiert deine Bilder und aktualisiert Inhalte...',
    'editItem.processingCompleted': 'Verarbeitung abgeschlossen!',
    'editItem.processingError': 'Bei der Verarbeitung ist ein Fehler aufgetreten.',
    'editItem.saleDisabledPlaceholder': 'Verkaufspreis eingeben',
    'editItem.rentalDisabledPlaceholder': 'Mietpreis eingeben',
    'editItem.primaryBadge': 'Hauptbild',
    // Image Upload Step
    'imageUpload.title': 'Bilder des Artikels hochladen',
    'imageUpload.description':
      'Füge Fotos deines Artikels hinzu, damit andere ihn besser finden und verstehen können.',
    'imageUpload.imagesUploaded': 'Bild hochgeladen',
    'imageUpload.imagesUploadedPlural': 'Bilder hochgeladen',
    'imageUpload.aiGenerating': 'KI generiert Inhalte…',
    'imageUpload.continueWithAI': 'Mit KI-Verarbeitung fortfahren',
    'imageUpload.skipAndContinue': 'KI überspringen, manuell fortfahren',
    'imageUpload.scanIsbn': 'Buch-ISBN scannen',
    'imageUpload.scanIsbnDescription':
      'Barcode eines Buchs scannen, um automatisch einen neuen Bucheintrag zu erstellen',
    'imageUpload.scanIsbnCreating': 'Buch wird von ISBN erstellt…',
    'imageUpload.scanIsbnSuccessTitle': 'Buch erstellt',
    'imageUpload.scanIsbnSuccessDescription':
      'Buchdetails wurden von der ISBN abgerufen. Du kannst jetzt die Details bearbeiten.',
    'imageUpload.scanIsbnErrorTitle': 'ISBN-Scan fehlgeschlagen',
    'imageUpload.scanIsbnErrorDescription':
      'Buch konnte nicht von ISBN erstellt werden. Bitte erneut versuchen.',

    // ImageManager UI text
    'imageManager.uploadInstructions':
      'Lade bis zu {max} Bilder hoch. Das erste Bild wird als Hauptbild verwendet.{drag}',
    'imageManager.dragToReorder': '(ziehen zum Neuordnen)',
    'imageManager.imagesLabel': 'Bilder',

    // ImageManager
    'imageManager.tooManyTitle': 'Zu viele Bilder',
    'imageManager.tooManyDescription': 'Maximal {max} Bilder erlaubt',
    'imageManager.invalidTypeTitle': 'Ungültiger Dateityp',
    'imageManager.invalidTypeDescription': 'Bitte wähle nur Bilddateien aus',
    'imageManager.fileTooLargeTitle': 'Datei zu groß',
    'imageManager.fileTooLargeDescription': 'Bilder müssen kleiner als 20MB sein',
    'imageManager.deleteSuccessTitle': 'Erfolg',
    'imageManager.deleteSuccessDescription': 'Bild erfolgreich gelöscht',
    'imageManager.deleteErrorTitle': 'Fehler',
    'imageManager.deleteErrorDescription': 'Bild konnte nicht gelöscht werden',
    'imageManager.rotateErrorTitle': 'Fehler',
    'imageManager.rotateErrorDescription': 'Bild konnte nicht gedreht werden',
    'imageManager.rotateLeft': 'Links drehen',
    'imageManager.rotateRight': 'Rechts drehen',

    // Requests
    'requests.title': 'Anfragen',
    'requests.noConversations': 'Noch keine Unterhaltungen',
    'requests.startConversation':
      'Beginne eine Unterhaltung, indem du jemanden wegen seines Artikels anschreibst!',
    'requests.typeMessage': 'Nachricht eingeben...',
    'requests.send': 'Senden',
    'requests.selectConversation': 'Wähle eine Unterhaltung aus, um zu chatten',

    // Common
    'common.loading': 'Lädt...',
    'common.error': 'Fehler',
    'common.loadingError': 'Fehler beim Laden',
    'common.cancel': 'Abbrechen',
    'common.save': 'Speichern',
    'common.saving': 'Speichert...',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.update': 'Aktualisieren',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.previous': 'Zurück',
    'common.submitting': 'Wird gesendet...',

    // Booking
    'booking.bookNow': 'Jetzt buchen',
    'booking.createBooking': 'Buchungsanfrage erstellen',
    'booking.createBookingDescription': 'Buchungsanfrage für {itemName} einreichen',
    'booking.purchaseOffer': 'Dein Kaufangebot',
    'booking.rentalOffer': 'Dein Mietangebot',
    'booking.totalPrice': 'Gesamtpreis',
    'booking.listedPrice': 'Gelisteter Preis',
    'booking.listedRentalPrice': 'Gelisteter Mietpreis',
    'booking.enterYourOffer': 'Gib deinen Angebotsbetrag ein',
    'booking.rentalStart': 'Mietbeginn Datum & Uhrzeit',
    'booking.rentalEnd': 'Mietende Datum & Uhrzeit',
    'booking.rentalEndOptional': 'Enddatum & Uhrzeit',
    'booking.rentalEndOptionalNote':
      'Kein Enddatum erforderlich — leer lassen für unbegrenzte Miete.',
    'booking.submitRequest': 'Anfrage senden',
    'booking.successTitle': 'Erfolg',
    'booking.successCreated': 'Buchungsanfrage erfolgreich erstellt!',
    'booking.errorCreate':
      'Erstellen der Buchungsanfrage fehlgeschlagen. Bitte versuche es erneut.',
    'booking.successUpdated': 'Buchung erfolgreich aktualisiert!',
    'booking.errorUpdate': 'Aktualisierung der Buchung fehlgeschlagen. Bitte versuche es erneut.',
    'requests.acceptWarningTitle': 'Bestätigung erforderlich',
    'requests.acceptWarningDescription':
      'Du akzeptierst ein Angebot in Höhe von {amount}. Dies wird bei Bestätigung der Anfrage endgültig.',

    // Calendar
    'calendar.selectRentalPeriod': 'Mietzeitraum auswählen',
    'calendar.time': 'Zeit',
    'calendar.clickToComplete': 'Klicke auf ein anderes Zeitfenster, um die Auswahl abzuschließen',
    'calendar.selectedPeriod': 'Ausgewählter Zeitraum',
    'calendar.from': 'Von',
    'calendar.to': 'Bis',
    'calendar.duration': 'Dauer',
    'calendar.hours': 'Stunden',
    'calendar.days': 'Tage',
    'calendar.selectingPeriod': 'Zeitraum wählen',
    'calendar.clickToSetEnd':
      'Klicke ein End-Feld zum Bestätigen oder bewege die Maus für eine Vorschau',
    'calendar.clearSelection': 'Zurücksetzen',
    'calendar.week': 'Woche',
    'calendar.month': 'Monat',

    // Requests Page
    'requests.allBookings': 'Alle Anfragen',
    'requests.noBookings': 'Noch keine Anfragen',
    'requests.selectBooking': 'Wähle eine Anfrage aus, um Details zu sehen',
    'requests.bookingDetails': 'Anfragedetails',
    'requests.bookingItem': 'Anfrage',
    'requests.unknownItem': 'Unbekannter Artikel',
    'requests.user': 'Benutzer',
    'requests.bookingId': 'Anfrage-ID',
    'requests.itemId': 'Artikel-ID',
    'requests.requestFrom': 'Anfrage von',
    'requests.requestTo': 'Anfrage an',
    'requests.offerAmount': 'Angebot',
    'requests.counterOffer': 'Gegenangebot',
    'requests.rentalPeriod': 'Mietzeitraum',
    'requests.noDate': 'Kein Datum angegeben',
    'requests.accept': 'Annehmen',
    'requests.acceptCounterOffer': 'Gegenvorschlag akzeptieren',
    'requests.reject': 'Ablehnen',
    'requests.cancel': 'Anfrage stornieren',
    'requests.noMessages': 'Noch keine Nachrichten',
    'requests.startConversation': 'Beginne die Konversation, indem du eine Nachricht sendest',
    'requests.messagesComingSoon': 'Nachrichtenfunktion kommt bald',
    'requests.messagesDescription': 'Hier kannst du bald über Anfragen chatten',
    'requests.typeMessage': 'Nachricht eingeben...',
    'requests.messages': 'Nachrichten',
    'requests.refresh': 'Aktualisieren',
    'requests.refreshing': 'Wird aktualisiert...',
    'requests.editBooking': 'Anfrage bearbeiten',
    'requests.editBookingDescription':
      'Bearbeite Mietzeitraum oder angebotenen Preis für diese Anfrage.',
    'requests.update': 'Aktualisieren',
    'requests.counterOfferDialogTitle': 'Gegenangebot machen',
    'requests.counterOfferDialogDescription':
      'Gib einen alternativen Preis ein, den du vorschlagen möchtest.',
    'requests.counterOfferSubmit': 'Gegenangebot senden',
    'requests.status.pending': 'Ausstehend',
    'requests.status.cancelled': 'Storniert',
    'requests.status.confirmed': 'Bestätigt',
    'requests.status.accepted': 'Angenommen',
    'requests.status.rejected': 'Abgelehnt',
    'requests.status.completed': 'Abgeschlossen',
    'requests.status.unknown': 'Unbekannt',

    // Bookings page
    'bookings.title': 'Meine Buchungen',
    'bookings.noBookings': 'Keine Buchungen gefunden',
    'bookings.gridView': 'Rasteransicht',
    'bookings.listView': 'Listenansicht',
    'bookings.filterAll': 'Alle',
    'bookings.filterOwner': 'Meine Artikel',
    'bookings.filterRenter': 'Gebuchte Artikel',
    'bookings.active': 'Aktiv',
    'bookings.upcoming': 'Bevorstehend',
    'bookings.past': 'Vergangen',
    'bookings.timeBooked': 'Gebuchte Zeit',
    'bookings.cost': 'Kosten',
    'bookings.dateFrom': 'Von',
    'bookings.dateTo': 'Bis',
    'bookings.dateRangeLabel': 'Zeitraum',
    'bookings.ongoing': 'Laufend',
    'bookings.user': 'Nutzer',
    'bookings.item': 'Artikel',
    'bookings.status': 'Status',
    'bookings.filterDateFrom': 'Startdatum',
    'bookings.filterDateTo': 'Enddatum',
    'bookings.resetFilters': 'Filter zurücksetzen',
    'bookings.endBooking': 'Buchung beenden',
    'bookings.prevPeriod': 'Vorheriger Zeitraum',
    'bookings.nextPeriod': 'Nächster Zeitraum',
    'bookings.today': 'Heute',
    'bookings.searchPlaceholder': 'Buchungen nach Artikel oder Person suchen…',
    'bookings.showPending': 'Ausstehende Anfragen anzeigen',
    'bookings.pending': 'Ausstehend',
    'bookings.directionPast': 'Vergangen',
    'bookings.directionUpcoming': 'Aktuell & bevorstehend',
    'bookings.perPage': 'Pro Seite',
    'bookings.noSearchResults': 'Keine Buchungen entsprechen deiner Suche',
    'bookings.searchingAll': 'Alle Buchungen durchsuchen – vergangen, aktuell & bevorstehend',
    'header.bookings': 'Buchungen',

    // Item Detail
    'itemDetail.backToItems': 'Zurück zu Artikeln',
    'itemDetail.editItem': 'Artikel bearbeiten',
    'itemDetail.deleteItem': 'Artikel löschen',
    'itemDetail.contactOwner': 'Besitzer kontaktieren',
    'itemDetail.buyNow': 'Kaufen',
    'itemDetail.rentNow': 'Mieten',
    'itemDetail.borrowNow': 'Buchen',
    'itemDetail.requestDonate': 'Anfragen',
    'itemDetail.itemDetails': 'Artikel Details',
    'itemDetail.description': 'Beschreibung',
    'itemDetail.listed': 'Gelistet',
    'itemDetail.location': 'Standort',
    'itemDetail.ownerInfo': 'Besitzer Informationen',
    'itemDetail.deleteConfirmTitle': 'Bist du sicher?',
    'itemDetail.deleteConfirmDescription':
      'Diese Aktion kann nicht rückgängig gemacht werden. Dieser Artikel wird dauerhaft gelöscht.',
    'itemDetail.notFound': 'Artikel nicht gefunden',
    'itemDetail.availability': 'Verfügbarkeit',
    'itemDetail.properties': 'Eigenschaften',
    'itemDetail.previousImage': 'Vorheriges Bild',
    'itemDetail.nextImage': 'Nächstes Bild',
    'itemDetail.openImage': 'Bild im Vollbild öffnen',
    'itemDetail.closeViewer': 'Bildansicht schließen',
    'itemDetail.goToImage': 'Zu Bild springen',

    // My Items
    'myItems.title': 'Meine Artikel',
    'myItems.noItems': 'Noch keine Artikel',
    'myItems.createFirst': 'Erstelle deinen ersten Artikel um loszulegen!',
    'myItems.shareItem': 'Artikel teilen',
    'myItems.status': 'Status',
    'myItems.changeStatus': 'Status ändern',
    'myItems.statusUpdated': 'Artikel Status erfolgreich aktualisiert',

    // Item Status
    'status.draft': 'Entwurf',
    'status.available': 'Verfügbar',
    'status.reserved': 'Reserviert',
    'status.rented': 'Vermietet',
    'status.sold': 'Vergeben',
    'status.unknown': 'Unbekannt',
    // Profile
    'profile.title': 'Profileinstellungen',
    'profile.manage': 'Verwalte deine Profilinformationen',
    'profile.name': 'Name',
    'profile.phone': 'Telefon',
    'profile.bio': 'Bio',
    'profile.address': 'Adresse',
    'profile.emailReminder': 'E-Mail-Erinnerungen',
    'profile.emailReminderDesc': 'E-Mail-Erinnerungen für Buchungen und Nachrichten erhalten',
    'profile.notifications': 'Benachrichtigungen',
    'profile.notificationsDesc': 'Externe Benachrichtigungskanäle konfigurieren',
    'profile.rocketchatNewMessage': 'Neue Nachricht via RocketChat',
    'profile.rocketchatNewMessageDesc':
      'RocketChat-Benachrichtigung bei neuer Nachricht in Bubble erhalten',
    'profile.appearance': 'Erscheinungsbild',
    'profile.themeAuto': 'Automatisch',
    'profile.language': 'Sprache',
    'profile.username': 'Benutzername',
    'profile.email': 'E-Mail',
    'profile.readOnly': 'Nur lesen',
    'profile.update': 'Profil aktualisieren',
    'profile.updating': 'Profil wird aktualisiert...',
    'editItem.invalidPricingTitle': 'Ungültige Preisangabe',
    'editItem.invalidPricingDescription':
      'Bitte setze entweder einen Verkaufspreis oder einen Mietpreis, nicht beides.',
    'editItem.updateSuccessTitle': 'Artikel aktualisiert',
    'editItem.updateSuccessDescription': 'Dein Artikel wurde erfolgreich aktualisiert.',
    'editItem.updateErrorTitle': 'Aktualisierung fehlgeschlagen',
    'editItem.updateErrorDescription':
      'Artikel konnte nicht aktualisiert werden. Bitte versuche es erneut.',
    'editItem.publishSuccessTitle': 'Artikel veröffentlicht',
    'editItem.publishSuccessDescription': 'Dein Artikel ist jetzt für die Community verfügbar.',
    'editItem.isbnUpdateSuccessTitle': 'Buch von ISBN aktualisiert',
    'editItem.isbnUpdateSuccessDescription':
      'Buchdetails wurden von OpenLibrary abgerufen und aktualisiert.',
    'editItem.isbnUpdateErrorTitle': 'ISBN-Aktualisierung fehlgeschlagen',
    'editItem.isbnUpdateErrorDescription':
      'Buchdaten konnten nicht von OpenLibrary abgerufen werden. Bitte versuche es erneut.',
    'editItem.isbnInvalidErrorTitle': 'Ungültige ISBN',
    'editItem.isbnInvalidErrorDescription':
      'Die eingegebene ISBN ist nicht gültig. Bitte überprüfe das Format und versuche es erneut.',
    'editItem.images': 'Bilder',
    'editItem.editBook': 'Buch bearbeiten',
    'editItem.bookDetails': 'Buch Details',
    'editItem.isbn': 'ISBN',
    'editItem.enterIsbn': 'ISBN eingeben',
    'editItem.year': 'Erscheinungsjahr',
    'editItem.enterYear': 'Jahr eingeben',
    'editItem.topic': 'Thema',
    'editItem.enterTopic': 'Thema oder Fachgebiet eingeben',
    'editItem.authors': 'Autoren',
    'editItem.selectAuthors': 'Autoren auswählen',
    'editItem.enterAuthors': 'Autoren eingeben (kommagetrennt)',
    'editItem.genres': 'Genres',
    'editItem.selectGenres': 'Genres auswählen',
    'editItem.enterGenres': 'Genres eingeben (kommagetrennt)',
    'editItem.publisher': 'Verlag',
    'editItem.selectPublisher': 'Verlag auswählen',
    'editItem.enterPublisher': 'Verlag eingeben',
    'editItem.shelf': 'Regal',
    'editItem.selectShelf': 'Regalstandort auswählen',
    'editItem.enterShelf': 'Regalstandort eingeben',
    'editItem.location': 'Standort',
    'editItem.selectLocation': 'Standort auswählen',
    'editItem.locationOwnerPlace': 'Beim Eigentümer',
    'editItem.locationLoading': 'Standorte werden geladen…',
    'rentalPeriod.h': 'Stündlich',
    'rentalPeriod.d': 'Täglich',
    'rentalPeriod.w': 'Wöchentlich',
    // User labels
    'user.name': 'Name',
    'user.email': 'E-Mail',
    // Scanner
    'scanner.open': 'Scanner öffnen',
    'scanner.title': 'Barcode scannen',
    'scanner.description': 'Positioniere den Barcode im Kamerabereich, um zu scannen',
    'scanner.usingNative': 'Verwendet native BarcodeDetector-API',
    'scanner.usingPolyfill': 'Verwendet barcode-detector Polyfill',
    'scanner.initializingCamera': 'Kamera wird initialisiert...',
    'scanner.detected': 'Erkannt',

    // Collections
    'collections.title': 'Sammlungen',
    'collections.myCollections': 'Meine Sammlungen',
    'collections.newCollection': 'Neue Sammlung',
    'collections.newCollectionShort': 'Neu',
    'collections.createCollection': 'Sammlung erstellen',
    'collections.name': 'Name',
    'collections.namePlaceholder': 'z.B. Campingausrüstung',
    'collections.slug': 'Slug',
    'collections.slugPlaceholder': 'z.B. campingausruestung',
    'collections.slugHelp':
      'Wird in der Sammlungs-URL verwendet. Standardmäßig aus dem Namen erzeugt.',
    'collections.description': 'Beschreibung',
    'collections.descriptionPlaceholder': 'Wofür ist diese Sammlung?',
    'collections.itemCount': '{count} Artikel',
    'collections.noCollections': 'Noch keine Sammlungen. Erstelle deine erste!',
    'collections.noItems': 'Noch keine Artikel in dieser Sammlung.',
    'collections.addToCollection': 'Zur Sammlung hinzufügen',
    'collections.removeFromCollection': 'Aus Sammlung entfernen',
    'collections.addedToCollection': 'Zur Sammlung hinzugefügt',
    'collections.removedFromCollection': 'Aus Sammlung entfernt',
    'collections.deleteCollection': 'Sammlung löschen',
    'collections.confirmDelete':
      'Möchtest du diese Sammlung wirklich löschen? Das kann nicht rückgängig gemacht werden.',
    'collections.editCollection': 'Sammlung bearbeiten',
    'collections.saveChanges': 'Änderungen speichern',
    'collections.permissions': 'Teilen & Berechtigungen',
    'collections.shareCollection': 'Sammlung teilen',
    'collections.grantAccess': 'Zugriff gewähren',
    'collections.grantPermission': 'Teilen',
    'collections.revokePermission': 'Entziehen',
    'collections.username': 'Benutzername',
    'collections.usernamePlaceholder': 'Benutzername eingeben',
    'collections.permission': 'Berechtigung',
    'collections.action': 'Aktion',
    'collections.backToCollections': 'Zurück zu Sammlungen',
    'collections.owner': 'Besitzer',
    'collections.created': 'Erstellt',
    'collections.header.myCollections': 'Meine Sammlungen',
    'collections.permissionsTab': 'Berechtigungen',
    'collections.detailsTab': 'Details',
    'collections.subjectTypeUser': 'Benutzer',
    'collections.subjectTypeGroup': 'Gruppe',
    'collections.groupName': 'Gruppe',
    'collections.groupPlaceholder': 'Gruppen suchen...',
    'collections.history': 'Sammlungsverlauf',
    'collections.historyButton': 'Verlauf',
    'collections.historyEmpty': 'Noch keine Ereignisse aufgezeichnet.',
    'collections.historyAdded': 'Hinzugefügt',
    'collections.historyRemoved': 'Entfernt',
    'collections.historyBy': 'von',
    'collections.appearsIn': 'Erscheint in Sammlungen',
    'collections.appearsInNone': 'In keiner Sammlung',
    'collections.currentGrants': 'Aktuelle Berechtigungen',
    'collections.noGrants': 'Noch keine Berechtigungen vergeben.',
    'collections.grantSubject': 'Benutzer / Gruppe',
    'collections.grantPermissionCol': 'Berechtigung',
    'collections.grantType': 'Typ',
    'collections.permUser': 'Benutzer',
    'collections.permGroup': 'Gruppe',
    'collections.roleView': 'Ansehen',
    'collections.roleEdit': 'Bearbeiten',
    'collections.roleOwner': 'Eigentümer',
    'collections.revokeGrant': 'Entziehen',
    'collections.ownerCannotRevoke':
      'Berechtigungen des Sammlungserstellers können nicht entfernt werden',
    'collections.searchPlaceholder': 'Sammlungen suchen...',
    'collections.onlyMine': 'Nur meine',
    'collections.viewList': 'Listenansicht',
    'collections.viewGrid': 'Rasteransicht',

    // Calendar subscription (CalDAV / iCalendar)
    'calendar.title': 'Kalender-Abo',
    'calendar.item.description':
      'Teile einen privaten Link, um die Buchungen dieses Artikels in jeder Kalender-App zu abonnieren, die iCalendar unterstützt. Ausstehende Buchungen erscheinen als vorläufig, bestätigte als belegt.',
    'calendar.collection.description':
      'Abonniere alle Buchungen dieser Sammlung in deiner Kalender-App. Jeder Eintrag zeigt den gebuchten Artikel und wer ihn gebucht hat.',
    'calendar.personal.title': 'Dein persönlicher Buchungskalender',
    'calendar.personal.description':
      'Füge diesen privaten CalDAV-Kalender zu deiner Kalender-App hinzu, um die Verfügbarkeit buchbarer Artikel zu sehen. Wenn du im Kalender eines Artikels einen Termin erstellst, wird daraus eine Buchungsanfrage für diese Zeit.',
    'calendar.copy': 'Link kopieren',
    'calendar.copied': 'Link in die Zwischenablage kopiert',
    'calendar.subscribe': 'Abonnieren',
    'calendar.subscribeTooltip': 'Kalender abonnieren',
    'calendar.regenerate': 'Link neu erstellen',
    'calendar.regenerateConfirm':
      'Neuen Link erstellen? Der aktuelle Link funktioniert dann sofort nicht mehr.',
    'calendar.regenerated': 'Ein neuer Kalender-Link wurde erstellt',
    'calendar.revoke': 'Deaktivieren',
    'calendar.revoked': 'Kalender-Link deaktiviert',
    'calendar.show': 'Kalender-Link anzeigen',
    'calendar.hide': 'Ausblenden',
    'calendar.secretHint': 'Jeder mit diesem Link kann den Kalender sehen — halte ihn privat.',
    'calendar.loadError': 'Kalender-Link konnte nicht geladen werden.',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    // First choice: use language as stored in localStorage (if the user has selected one)
    const savedLang = localStorage.getItem('bubble-language');
    if (savedLang && LANGUAGES.includes(savedLang as Language)) {
      return savedLang as Language;
    }

    // Second choice: use the first available language from the user's browser / OS preferences
    for (const lang of navigator.languages) {
      // remove suffixes from languages like "de-AT"
      const baseLang = lang.split('-')[0];
      if (LANGUAGES.includes(baseLang as Language)) {
        return baseLang as Language;
      }
    }

    // Third choice: fallback to English
    return 'en';
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('bubble-language', lang);
  }, []);

  const syncLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('bubble-language', lang);
  }, []);

  const t = useCallback(
    (key: string): string => {
      return translations[language][key as keyof (typeof translations)['en']] || key;
    },
    [language],
  );

  const value = useMemo(
    () => ({ language, setLanguage, syncLanguage, t }),
    [language, setLanguage, syncLanguage, t],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
