# Generated by Django 6.1 on 2026-09-22 20:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


LEDGER_ADMIN_GROUP = "ledger_admin"


def create_treasurer_group(apps, schema_editor):
    # Members of this group may post payouts and community income and reverse
    # anyone's transaction. Membership is managed in the Django admin.
    apps.get_model("auth", "Group").objects.get_or_create(name=LEDGER_ADMIN_GROUP)


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("ledger", "0002_seed_default_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="kind",
            field=models.IntegerField(
                choices=[
                    (1, "Booking charge"),
                    (2, "Member expense"),
                    (3, "Shared expense"),
                    (4, "Top-up"),
                    (5, "Payout"),
                    (6, "Membership fee"),
                    (7, "Adjustment"),
                    (8, "Opening balance"),
                    (9, "Reversal"),
                    (10, "Correction"),
                    (11, "Between members"),
                    (12, "Income"),
                ]
            ),
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("file_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("content", models.BinaryField()),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="ledger.transaction",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_receipts",
                        to="ledger.account",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceiptAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accessed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_accesses",
                        to="ledger.account",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accesses",
                        to="ledger.receipt",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "receipt accesses",
                "ordering": ["-accessed_at"],
            },
        ),
            # Kept on rollback: the group may have members by then.
        migrations.RunPython(create_treasurer_group, migrations.RunPython.noop),
        # Receipts document the books and their access log is an audit trail:
        # both are append-only, like transactions and entries.
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER ledger_receipt_append_only
                BEFORE UPDATE OR DELETE ON ledger_receipt
                FOR EACH ROW EXECUTE FUNCTION ledger_forbid_change();

            CREATE TRIGGER ledger_receiptaccess_append_only
                BEFORE UPDATE OR DELETE ON ledger_receiptaccess
                FOR EACH ROW EXECUTE FUNCTION ledger_forbid_change();
            """,
            reverse_sql="""
            DROP TRIGGER ledger_receiptaccess_append_only ON ledger_receiptaccess;
            DROP TRIGGER ledger_receipt_append_only ON ledger_receipt;
            """,
        ),
    ]
