# Generated by Django 6.1 on 2026-09-24 07:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seal_existing(apps, schema_editor):
    """Seal the transactions posted before the chain existed, in seq order.

    Uses the same canonical form as ``bubble.ledger.chain``, so a later
    verification recomputes these hashes like any other.
    """
    from bubble.ledger.chain import GENESIS, link_hash  # noqa: PLC0415

    Book = apps.get_model("ledger", "Book")
    Transaction = apps.get_model("ledger", "Transaction")
    TransactionSeal = apps.get_model("ledger", "TransactionSeal")
    for book in Book.objects.all():
        prev = GENESIS
        transactions = (
            Transaction.objects.filter(book=book)
            .prefetch_related("entries")
            .order_by("seq")
        )
        for position, tx in enumerate(transactions.iterator(chunk_size=500), 1):
            digest = link_hash(prev, tx)
            TransactionSeal.objects.create(
                transaction=tx,
                book=book,
                position=position,
                prev_hash=prev,
                hash=digest,
            )
            prev = digest


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0004_disputes_comments_cost_shares"),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerDigest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("position", models.BigIntegerField()),
                ("head_hash", models.CharField(max_length=64)),
                ("transaction_count", models.BigIntegerField()),
                (
                    "chain_ok",
                    models.BooleanField(
                        help_text="The whole chain was recomputed and matched when this was made."
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False,
                        help_text="Sent to the configured digest channel.",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="digests",
                        to="ledger.book",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
            },
        ),
        migrations.CreateModel(
            name="TransactionSeal",
            fields=[
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="seal",
                        serialize=False,
                        to="ledger.transaction",
                    ),
                ),
                (
                    "position",
                    models.BigIntegerField(help_text="1 for the first transaction."),
                ),
                ("prev_hash", models.CharField(max_length=64)),
                ("hash", models.CharField(max_length=64)),
                ("sealed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seals",
                        to="ledger.book",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("book", "position"),
                        name="ledger_seal_position_per_book",
                    ),
                    models.UniqueConstraint(
                        fields=("book", "prev_hash"), name="ledger_seal_no_fork"
                    ),
                ],
            },
        ),
            migrations.RunSQL(
            sql="""
            CREATE TRIGGER ledger_transactionseal_append_only
                BEFORE UPDATE OR DELETE ON ledger_transactionseal
                FOR EACH ROW EXECUTE FUNCTION ledger_forbid_change();
            CREATE TRIGGER ledger_ledgerdigest_append_only
                BEFORE UPDATE OR DELETE ON ledger_ledgerdigest
                FOR EACH ROW EXECUTE FUNCTION ledger_forbid_change();
            """,
            reverse_sql="""
            DROP TRIGGER ledger_transactionseal_append_only
                ON ledger_transactionseal;
            DROP TRIGGER ledger_ledgerdigest_append_only ON ledger_ledgerdigest;
            """,
        ),
        migrations.RunPython(seal_existing, migrations.RunPython.noop),
    ]
