# Generated by Django 6.1 on 2026-09-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0005_hash_chain"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="datev_number",
            field=models.CharField(
                blank=True,
                help_text="Account number in the tax advisor's chart (DATEV export). Member accounts may leave it empty to use the shared member account.",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="ledgerperiod",
            name="chain_head",
            field=models.CharField(
                blank=True,
                help_text="Head of the hash chain when the period was closed.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="ledgerperiod",
            name="chain_position",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ledgerperiod",
            name="transaction_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ledgerperiod",
            name="export_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 of the journal export of the period at closing.",
                max_length=64,
            ),
        ),
    ]
