# Generated by Django 6.1 on 2026-09-24 07:31

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


def give_references(apps, schema_editor):
    """Every existing member account gets its bank transfer reference."""
    import secrets  # noqa: PLC0415

    alphabet = "23456789ABCDEFGHJKMNPQRSTUVWXYZ"
    Account = apps.get_model("ledger", "Account")
    used = set(
        Account.objects.exclude(payment_reference="").values_list(
            "payment_reference", flat=True
        )
    )
    for account in Account.objects.filter(type=1, payment_reference=""):
        while True:
            reference = "BUB-" + "".join(secrets.choice(alphabet) for _ in range(6))
            if reference not in used:
                break
        used.add(reference)
        account.payment_reference = reference
        account.save(update_fields=["payment_reference"])


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0006_period_close_and_datev"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalStatementLine",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        help_text="Recognises the same line in overlapping files.",
                        max_length=64,
                    ),
                ),
                ("booked_on", models.DateField()),
                ("value_date", models.DateField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                ("counterparty_name", models.CharField(blank=True, max_length=255)),
                ("counterparty_iban", models.CharField(blank=True, max_length=34)),
                ("reference", models.TextField(blank=True)),
                ("end_to_end_id", models.CharField(blank=True, max_length=100)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "To review"),
                            ("booked", "Booked"),
                            ("linked", "Matched to an entry"),
                            ("suspense", "Parked, to be clarified"),
                            ("ignored", "Ignored"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "Payment reference"),
                            ("medium", "Known account"),
                            ("low", "Similar name"),
                            ("none", "No match"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical statement line",
                "verbose_name_plural": "historical statement lines",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="KnownIban",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iban", models.CharField(max_length=34)),
                ("learned_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StatementImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(help_text="Adapter, e.g. camt053.", max_length=20),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("sha256", models.CharField(max_length=64)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("line_count", models.PositiveIntegerField(default=0)),
                ("new_line_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-imported_at"],
            },
        ),
        migrations.CreateModel(
            name="StatementLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        help_text="Recognises the same line in overlapping files.",
                        max_length=64,
                    ),
                ),
                ("booked_on", models.DateField()),
                ("value_date", models.DateField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                ("counterparty_name", models.CharField(blank=True, max_length=255)),
                ("counterparty_iban", models.CharField(blank=True, max_length=34)),
                ("reference", models.TextField(blank=True)),
                ("end_to_end_id", models.CharField(blank=True, max_length=100)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "To review"),
                            ("booked", "Booked"),
                            ("linked", "Matched to an entry"),
                            ("suspense", "Parked, to be clarified"),
                            ("ignored", "Ignored"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "Payment reference"),
                            ("medium", "Known account"),
                            ("low", "Similar name"),
                            ("none", "No match"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-booked_on", "-amount"],
            },
        ),
        migrations.AddField(
            model_name="account",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                help_text="Member accounts: the reference to put on bank transfers, so an imported statement line finds its member (plan section 12).",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(("payment_reference", ""), _negated=True),
                fields=("book", "payment_reference"),
                name="ledger_payment_reference_per_book",
            ),
        ),
        migrations.AddField(
            model_name="historicalstatementline",
            name="book",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ledger.book",
            ),
        ),
        migrations.AddField(
            model_name="historicalstatementline",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalstatementline",
            name="proposed_account",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ledger.account",
            ),
        ),
        migrations.AddField(
            model_name="historicalstatementline",
            name="proposed_transaction",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="An entry already posted by hand that this line pays for.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ledger.transaction",
            ),
        ),
        migrations.AddField(
            model_name="historicalstatementline",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ledger.account",
            ),
        ),
        migrations.AddField(
            model_name="historicalstatementline",
            name="settlement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The entry that moved a parked line out of suspense.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ledger.transaction",
            ),
        ),
        migrations.AddField(
            model_name="historicalstatementline",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The entry that booked or matched this line.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ledger.transaction",
            ),
        ),
        migrations.AddField(
            model_name="knowniban",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="known_ibans",
                to="ledger.account",
            ),
        ),
        migrations.AddField(
            model_name="knowniban",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ledger.book",
            ),
        ),
        migrations.AddField(
            model_name="statementimport",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="imports",
                to="ledger.book",
            ),
        ),
        migrations.AddField(
            model_name="statementimport",
            name="imported_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ledger.account",
            ),
        ),
        migrations.AddField(
            model_name="historicalstatementline",
            name="statement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ledger.statementimport",
            ),
        ),
        migrations.AddField(
            model_name="statementline",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bank_lines",
                to="ledger.book",
            ),
        ),
        migrations.AddField(
            model_name="statementline",
            name="proposed_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ledger.account",
            ),
        ),
        migrations.AddField(
            model_name="statementline",
            name="proposed_transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="An entry already posted by hand that this line pays for.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ledger.transaction",
            ),
        ),
        migrations.AddField(
            model_name="statementline",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ledger.account",
            ),
        ),
        migrations.AddField(
            model_name="statementline",
            name="settlement",
            field=models.ForeignKey(
                blank=True,
                help_text="The entry that moved a parked line out of suspense.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ledger.transaction",
            ),
        ),
        migrations.AddField(
            model_name="statementline",
            name="statement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lines",
                to="ledger.statementimport",
            ),
        ),
        migrations.AddField(
            model_name="statementline",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="The entry that booked or matched this line.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bank_lines",
                to="ledger.transaction",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowniban",
            constraint=models.UniqueConstraint(
                fields=("book", "iban"), name="ledger_iban_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="statementimport",
            constraint=models.UniqueConstraint(
                fields=("book", "sha256"), name="ledger_import_once_per_file"
            ),
        ),
        migrations.AddIndex(
            model_name="statementline",
            index=models.Index(
                fields=["book", "state"], name="ledger_stat_book_id_2e9190_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="statementline",
            constraint=models.UniqueConstraint(
                fields=("book", "fingerprint"), name="ledger_bank_line_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="statementline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("transaction__isnull", False)),
                fields=("transaction",),
                name="ledger_bank_line_one_per_transaction",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="kind",
            field=models.IntegerField(
                choices=[
                    (1, "Booking charge"),
                    (2, "Member expense"),
                    (3, "Shared expense"),
                    (4, "Top-up"),
                    (5, "Payout"),
                    (6, "Membership fee"),
                    (7, "Adjustment"),
                    (8, "Opening balance"),
                    (9, "Reversal"),
                    (10, "Correction"),
                    (11, "Between members"),
                    (12, "Income"),
                    (13, "Expense"),
                ]
            ),
        ),
        migrations.RunPython(give_references, migrations.RunPython.noop),
    ]
