# Generated by Django 6.0.3 on 2026-03-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_enable_rocketchat_for_existing_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpreference",
            name="event_type",
            field=models.CharField(
                choices=[("new_message", "New Message"), ("new_item", "New Item")],
                max_length=50,
                verbose_name="event type",
            ),
        ),
    ]
