# Generated by Django 6.0.6 on 2026-06-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notificationpreference_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpreference",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("new_message", "New Message"),
                    ("new_booking", "New Booking"),
                    ("new_item", "New Item"),
                ],
                max_length=50,
                verbose_name="event type",
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("rocketchat", "RocketChat"),
                    ("signal", "Signal"),
                    ("email", "Email"),
                ],
                max_length=50,
                verbose_name="provider type",
            ),
        ),
    ]
