# Generated by Django 6.0.6 on 2026-06-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_backfill_apprise_rocketchat_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpreference",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("rocketchat", "RocketChat"),
                    ("signal", "Signal"),
                    ("matrix", "Matrix"),
                    ("email", "Email"),
                ],
                max_length=50,
                verbose_name="provider type",
            ),
        ),
    ]
