# Generated by Django 6.1 on 2026-08-17 15:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_alter_notificationpreference_provider_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpreference",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("rocketchat", "RocketChat"),
                    ("signal", "Signal"),
                    ("matrix", "Matrix"),
                    ("email", "Email"),
                    ("webpush", "Browser push"),
                ],
                max_length=50,
                verbose_name="provider type",
            ),
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "endpoint",
                    models.URLField(
                        max_length=500, unique=True, verbose_name="endpoint"
                    ),
                ),
                (
                    "p256dh",
                    models.CharField(max_length=255, verbose_name="client public key"),
                ),
                (
                    "auth",
                    models.CharField(max_length=255, verbose_name="client auth secret"),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reported by the browser at subscribe time, to tell devices apart.",
                        max_length=300,
                        verbose_name="user agent",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time a notification was accepted by the push service.",
                        null=True,
                        verbose_name="last used at",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Push Subscription",
                "verbose_name_plural": "Push Subscriptions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_2bc4e1_idx",
                    )
                ],
            },
        ),
    ]
