# Generated by Django 6.1 on 2026-09-23 12:02

from django.db import migrations, models


def copy_message_preferences(apps, schema_editor):
    """Ledger activity joins the "messages" group: keep that toggle as it was.

    The group toggle reads as on only when every event in it is enabled, so
    every channel where new messages are on gets ledger notifications too.
    """
    Preference = apps.get_model("notifications", "NotificationPreference")
    for pref in Preference.objects.filter(event_type="new_message").iterator():
        Preference.objects.update_or_create(
            user_id=pref.user_id,
            provider_type=pref.provider_type,
            event_type="ledger",
            defaults={"enabled": pref.enabled},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_pushsubscription_and_webpush_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpreference",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("new_message", "New Message"),
                    ("new_booking", "New Booking"),
                    ("new_item", "New Item"),
                    ("ledger", "Community ledger"),
                ],
                max_length=50,
                verbose_name="event type",
            ),
        ),
        migrations.RunPython(copy_message_preferences, migrations.RunPython.noop),
    ]
