# Generated by Django 6.0.6 on 2026-06-16 07:39

import bubble.caldav.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0005_booking_ap_id_booking_remote_booker_actor_and_more"),
        ("collections", "0004_collection_slug"),
        ("items", "0013_historicalitem_ap_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("item", "Item feed"),
                            ("collection", "Collection feed"),
                            ("user", "Personal CalDAV"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        db_index=True,
                        default=bubble.caldav.models.generate_secret,
                        editable=False,
                        help_text="Non-guessable secret embedded in the calendar URL.",
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_links",
                        to="collections.collection",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_links",
                        to="items.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalDAVObject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resource_name",
                    models.CharField(
                        help_text="Client-chosen .ics file name within the calendar collection.",
                        max_length=255,
                    ),
                ),
                ("uid", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caldav_object",
                        to="bookings.booking",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caldav_objects",
                        to="items.item",
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caldav_objects",
                        to="caldav.calendarlink",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="calendarlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "item")),
                fields=("item",),
                name="uniq_item_calendar_link",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "collection")),
                fields=("collection",),
                name="uniq_collection_calendar_link",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "user")),
                fields=("user",),
                name="uniq_user_calendar_link",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarlink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("collection__isnull", True),
                        ("item__isnull", False),
                        ("kind", "item"),
                    ),
                    models.Q(
                        ("collection__isnull", False),
                        ("item__isnull", True),
                        ("kind", "collection"),
                    ),
                    models.Q(
                        ("collection__isnull", True),
                        ("item__isnull", True),
                        ("kind", "user"),
                    ),
                    _connector="OR",
                ),
                name="calendar_link_target_matches_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="caldavobject",
            constraint=models.UniqueConstraint(
                fields=("link", "item", "resource_name"),
                name="uniq_caldav_object_resource",
            ),
        ),
    ]
